### ISSUE TITLE
Update Readme & Windows Setup Instructions

### ISSUE THREAD

**Issue by blindsteal** [PSPDFKit/react-native#112]
So after spending a solid 3 house trying to get your basic example to run, here are some notes that might help you improve the instructions for future newbies.

* The UWP announcement link at the top of the Readme is broken.
* UWP Setup is missing a step where you add the PSPDFKit Package to `MainReactNativeHost.cs`. This causes "native package not found errors".
* Instead of manually changing the RN version, you can just run `react-native init --version=0.53.0 MyApp`.
* I kept getting errors about some system libraries missing. This is due to wrong target/min SDK settings. There is a RN-Windows ticket somewhere which tells you to retarget ChakraCore to at least 1439, but I think I also had to retarget some of the other projects in the solution.
* The sample code in the Readme will make the app crash with a null pointer exception when running. Looking at the catalog sample, I figured you have to pass a `document` URL to `PSPDFKitView`. Is this expected behaviour?

All in all, this experience does not fill me with confidence regarding PSPDFKits commitment to RN, especially Windows UWP...

**Comment by blindsteal** [comment]
Also, two more things:
* I had to manually change the PSPDFKit-SDK version required by the RN Module... Maybe a timing issue with release of the VS Plugin and yesterday's "update Windows SDK"-Commit?
* I still haven't managed to get the build working with `react-native run-windows`. Throws some ChakraCore error. VS Code Deploy & Run works fine though.

**Comment by nickwinder** [comment]
Hi @blindsteal,
Thanks for bringing these issues to our attention. I've made some of the changes to the README that you have suggested and I'll produce a PR for these. I'm also looking into the outstanding issues you've found with SDK versioning and `PSPDFKitView` `document` necessity. I'll get back in touch with the findings and produce a separate PR if required.  

I'd also like to invite you to produce PR's if you would desire, as this is an open source repo and we are always interested in gathering knowledge and suggestions from our users and ways in which it is being used. Thanks

**Comment by nickwinder** [comment]
The two PR's are merged now. So I'll close this issue. Feel free to open new issues with specific issues if you feel there is anything else that needs addressing.
Thanks
