### ISSUE TITLE
Cannot find the option to hide the Document Info on Android

### ISSUE THREAD

**Issue by khoatran121294** [PSPDFKit/react-native#121]
Hi team,

Currently, I'm developing a app using PSPDFKit with latest version 7.7. Customer want me to hide the document info view on the right bar. On iOS I can hide it well, but I cannot find any features to hide it on Android. I'm following based on file ConfigurationAdapter.java: 
https://github.com/PSPDFKit/react-native/blob/master/android/src/main/java/com/pspdfkit/react/ConfigurationAdapter.java.

Looking forward to receiving your feedback soon.

Thanks,
Khoa

**Comment by irgendeinich** [comment]
Hey,
could you provide a screenshot of the document info view you're talking about, because I'm not aware of any document info view on the Android side.

**Comment by khoatran121294** [comment]
Hi @irgendeinich, 
Sorry for my shortcomings. Currently, I hide the button Information on iOS:
<img width="233" alt="screen shot 2018-08-21 at 11 18 31 pm" src="https://user-images.githubusercontent.com/13750945/44411504-3b673900-a599-11e8-96e7-ab533a657d0d.png">

But I cannot hide it on Android, you can see the button Information as below:
<img width="274" alt="screen shot 2018-08-21 at 11 16 38 pm" src="https://user-images.githubusercontent.com/13750945/44411544-546fea00-a599-11e8-856d-926f1ca6026e.png">

**Comment by irgendeinich** [comment]
Just letting you know that we now have a `showDocumentInfoView` property you can set on the configuration object. Just update your wrapper and you should be good to go.

**Comment by khoatran121294** [comment]
Hi @irgendeinich,
Many thanks for your update. But after I update this version, I encounter an
 issue related to authorization as below:
<img width="519" alt="screen shot 2018-08-22 at 10 04 09 pm" src="https://user-images.githubusercontent.com/13750945/44468940-f86c9a80-a658-11e8-8217-1ba372c2ff15.png">

Could you guide me to resolve this issue soon?
Thanks,
Khoa

**Comment by radazzouz** [comment]
@khoatran121294 this looks like a separate issue. Please reach out to pspdfkit.com/support/request and our support team will help you in there.
