### ISSUE TITLE
Open a Remote Linearized PDF Document

### ISSUE THREAD

**Issue by shaliko** [PSPDFKit/react-native#124]
For able to implement Lazy loading big PDF files. As example load only 10 first pages and when user scroll document, load next 10 pages and etc..

**Comment by radazzouz** [comment]
Hi @shaliko,

We do not support streaming PDFs (downloading bits at a time for a remote document). This is something that we are considering for the future.

The best and easiest way to accomplish this, is to download the PDF first before presenting it. We recommend using local file system documents for a better performance, cache control, battery impact, etc.

See our Document Downloads documentation here:

**Android:** https://pspdfkit.com/guides/android/current/miscellaneous/document-downloads/
**iOS:** https://pspdfkit.com/guides/ios/current/miscellaneous/document-downloads/

In the future, please reach out to our support channel (pspdfkit.com/support/request/).

Thank you!
