### ISSUE TITLE
Cannot submit app to App Store

### ISSUE THREAD

**Issue by khoatran121294** [PSPDFKit/react-native#146]
Hi team,

Currently, I've done for developing the app, but when to submit the app to review on App Store, it is rejected by Apple team. It seems related to something from UIBackgroundMode but I don't know where used it. Can you help me to pass this case?

![image](https://user-images.githubusercontent.com/13750945/48594804-1e21eb00-e98d-11e8-880d-fde3031a4deb.png)

Thanks,
Khoa

**Comment by steipete** [comment]
Khoa,

PSPDFKit includes code for background audio playback to support sound annotations.
We've documented this requirement here: https://pspdfkit.com/guides/ios/current/getting-started/permissions/

Apple might request information about how it can test UIBackgroundModes — simply attach a sample PDF that contains sound to this request. The file provided here contains copyright-free sample music and can be used to test sound annotations. Just make sure you don’t accidentally disable sound annotations by excluding them from -[PSPDFDocument renderAnnotationTypes].

https://cl.ly/0R43200T102r
