### ISSUE TITLE
PdfView crashes instantly with react-native-windows

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#149]
**Environment**

- react-native-windows app
- pspdfkit for uwp version 1.7.1 and 1.8.0 (tried both)
- resolved yarn dependency:
```
"react-native-pspdfkit@github:PSPDFKit/react-native":
  version "1.22.0"
  resolved "https://codeload.github.com/PSPDFKit/react-native/tar.gz/76eb9961cbcb2960a35bee2b7d229ef8c7248271"
```

**Current**
The app crashes with the following warning:
![pspdfkit-error](https://user-images.githubusercontent.com/9424038/49933604-62d96d00-fecc-11e8-9daf-1c73f62dff35.PNG)

**Expected**
The pdf viewer should open and display the pdf file.

**Comment by leoek** [comment]
With pspdfkit for uwp 1.6.1 and this version in my yarn lockfile:

```
"react-native-pspdfkit@github:PSPDFKit/react-native":
  version "1.20.0"
  resolved "https://codeload.github.com/PSPDFKit/react-native/tar.gz/3009bbedda33c348a393118dd1bf44dd50fa9f8a"
```

my app works as expected. I encountered the error first, after the upgrade to 1.7.

**Comment by nickwinder** [comment]
@leoek Thanks for getting back to us with your findings. 
I've spent sometime updating our sources to support PSPDFKit for Windows 1.8, and in addition to this ensured that our dependencies align with iOS and Android, therefore the `react-native-windows` dependency is now set at `0.55.0-rc.0`. With this change there were a fair few updates to the project Visual Studio project. 
You can see all the is work in https://github.com/PSPDFKit/react-native/pull/151 which I hope to get reviewed and merged shortly. 

To diagnose your issue I may need some additional information. 
- Could I ensure that you are able to run the Catalog application in the repo? You can find instructions on how to do this https://github.com/PSPDFKit/react-native#running-catalog-project-2, or if you want to try SDK 1.8 you can try https://github.com/PSPDFKit/react-native/blob/dbc4f8b32c702f48fd1fc24a5a7ed0ac98e0ec5c/README.md#running-catalog-project-2 which has been slightly simplified. 
- I understand it is not possible to disclose your application but is it possible to produce a minimal test project so we can reproduce the issue? From the error it seems as the UI module for PSPDFKit has not been registered with react native but with no source it's very difficult to know. I need to ensure that Windows target SDK and minimum SDK are set correctly. The package has been registered in `MainReactNativeHost.cs` and how the `index.js` is declaring the `PDFView`. 

Thanks

**Comment by leoek** [comment]
Hi @nickwinder sorry for my delayed response. I had only very little time to try and reproduce and track down this issue in the past weeks.

I think this was happening due to some weird behavior of visual studio... I could reproduce it on a second windows machine, however it seems to work on every other machine.

Thank you for upgrading to a newer pspdfkit version anyways!
