### ISSUE TITLE
Cannot download older version of the pspdfkit for uwp extension

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#150]
The download page does not offer any option to download older versions of the extension.

This is an issue because the version which is currently downloaded is 1.8.0, however this repo still references 1.7.1.

Also this repo should introduce git tags with the versions which should be used together with a certain version of the pspdfkit for uwp extension.

Having no git tags and older artifacts of the extension will make bugs like #149 even worse because there is no proper option to use the last working configuration.

**Comment by nickwinder** [comment]
Thanks for the advice and suggestions. I also think tags are a good idea going forward and I'll ensure that is implemented. 

As for retrieving old SDK builds always feel free to contact support if you do have requests like this. You can contact Richard@pspdfkit.com directly and he will be able to help with this. 

I will be looking into https://github.com/PSPDFKit/react-native/issues/149 to diagnose the issue.
