### ISSUE TITLE
Allow UWP setters to throw errors to a promise

### ISSUE THREAD

**Issue by nickwinder** [PSPDFKit/react-native#169]
Currently, all getters throw an error to the promise if any error occurs in the native UWP code which allows for easy handling in react native. The behavior is not reflected in the setters making it a little difficult to catch errors. 

# Acceptance Criteria

- [x] Promise for `saveCurrentDocument`
- [ ] Promise for `exitCurrentlyActiveMode`
- [ ] Promise for `enterAnnotationCreationMode`
- [x] Promise for `addAnnotation`

**Comment by leoek** [comment]
This is exactly what we need.

If I open a new pdf with `PSPDFKit.Present(path);` and try to add annotations with `addAnotation(annotation)` after opening the pdf, the app will crash with the following error:
```
System.Exception: 'Exception while trying to CreateAnnotationAsyncInternal: Instance is undefined'
```

This can be mitigated with a timeout which just waits x seconds after opening the pdf, to be sure that the instance is not undefined any more. However this is a very hacky workaround which we cannot use in production. (It will fail for big pdfs even with that workaround, annotations appear delayed.)

**Comment by leoek** [comment]
@nickwinder Do you have a timeline on this feature? The promise and error handling for addAnnotation is pretty important for us. In the last version we tested, we had a lot of crashes while adding annotations.

**Comment by nickwinder** [comment]
As this is currently a small blocker for you I'll add it on the list for the end of the week and hope to have something merged by next week. Would this be ok for you?

**Comment by leoek** [comment]
Yes, that would be good. Thanks!
