### ISSUE TITLE
☂️Update for React Native 0.59

### ISSUE THREAD

**Issue by radazzouz** [PSPDFKit/react-native#182]
# Details:

[React Native 0.59](https://github.com/facebook/react-native/releases/tag/v0.59.0) is out! We need to make sure that everything works great with the new version.

# Acceptance Criteria:

## Android:

- [x] A newly created app works with React Native 0.59.
- [x] The Catalog sample project works with React Native 0.59.

## iOS:

- [x] A newly created app works with React Native 0.59.
- [x] A newly created app works with React Native 0.59 when using the CocoaPods integration.
- [x] The Catalog sample project works with React Native 0.59. See https://github.com/PSPDFKit/react-native/pull/193

## Windows:

Windows now has 0.59 support and can be completed.

- [ ] A newly created app works with React Native 0.59.
- [ ] The Catalog sample project works with React Native 0.59

**Comment by nickwinder** [comment]
Currently, not possible while the migration from react native UWP to React native windows in C++ is in process. See https://github.com/microsoft/react-native-windows#status for a status update.

**Comment by leoek** [comment]
@nickwinder react-native-windows has RN 0.59 support now.

**Comment by nickwinder** [comment]
@leoek Nice! I was worried that `current` branch in `react-native-windows` was going to die without any updates. It's a shame it's not 0.60.
Thanks for the ping.

**Comment by leoek** [comment]
@nickwinder RN 60 support is planned for fall to winter 2019.

**Comment by nickwinder** [comment]
I'm not 100% that it's going to be back-ported though. https://github.com/microsoft/react-native-windows/issues/2786
It seems that it's only staged for `vnext` work.

**Comment by leoek** [comment]
@nickwinder If I remember correctly I have read that they will maintain current until vnext is stable and has all the feature which current has at the moment.

The visualization on this page also shows RN 60 for current: https://github.com/microsoft/react-native-windows/blob/master/blog/Roadmap2019.md

**Comment by leoek** [comment]
@nickwinder with https://github.com/microsoft/react-native-windows/issues/2899 and eact-native-windows 0.59-rc.3 this can be completed now.

**Comment by nickwinder** [comment]
@leoek thanks for the reminder. We'll get to it this week to see if there are any blockers. In the meantime feel free to fork and upgrade the package yourself if this is a blocker.

**Comment by nickwinder** [comment]
@leoek react native Windows 0.59 is now supported on the https://github.com/PSPDFKit/react-native/tree/windows-support branch. This branch will be kept alive until we can bring react native Windows back in line with Android and iOS (0.60) support. 
iOS and Android were also tested with 0.59 on this branch and are still known to work.
