### ISSUE TITLE
[UWP] Toolbar color not configurable?

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#184]
Is the color (text and background) of the toolbar configurable? I tried to set it through the style property, which didn't work.

```
const styles = StyleSheet.create({
  page: {
    flex: 1,
    alignItems: "stretch",
    backgroundColor: "#eee"
  },
  pdfView: {
    flex: 1,
    backgroundColor: "#111111",
    color: "#ffffff"
  }
});

...

const { exists, status, isResolving, isResolved, selected } = this.props;
    return (
      <View style={styles.page}>
        <PdfViewStatusBar />
        <PSPDFKitView
          ref="pdfView"
          }}
          style={styles.pdfView}
          onAnnotationsChanged={this.handleAnnotationsChanged}
          //document="ms-appx:///Assets/pdfs/app-konzept.pdf"
        />
      </View>
    );

```

**Comment by nickwinder** [comment]
This would require extra API as the css would have to be passed via PSPDFKit for Windows. 
You can see the Windows guide for CSS customization https://pspdfkit.com/guides/windows/current/customizing-the-interface/css-customization/?search=custom which makes general customization fairly simple. 

I will look into implementing the feature and what would be required.

**Comment by leoek** [comment]
it would be very cool if we could supply the css through the js react-native wrapper.

**Comment by nickwinder** [comment]
@leoek the feature is now merged. See https://github.com/PSPDFKit/react-native/blob/cc79c17d2f823dbe9741b527d3a71bcf1c7b58f6/samples/Catalog/Catalog.windows.js#L460 component in the catalog for an example. 
I hope this works well for you.

**Comment by leoek** [comment]
@nickwinder Thanks!

Would be great if you could bump the version to 1.23.3.

**Comment by nickwinder** [comment]
@leoek Currently windows changes do not track the same versioning as iOS and Android as explained in https://github.com/PSPDFKit/react-native/issues/173#issuecomment-474359004. 
Therefore the versioning will follow the PSPDFKit for Windows version.

**Comment by leoek** [comment]
@nickwinder Which is fine for the git tags. However the version is not properly tracked/resolved in the yarn.lock.

**Current**
If I lock the version to 1.23.2 I cannot be certain whether it will resolve to something with or without your changes. Because the version in the package.json was 1.23.2 before your changes and is still 1.23.2...

That's why I would want an update to the version in the package.json to 1.23.3, which avoids these situations: https://github.com/PSPDFKit/react-native/issues/173#issuecomment-474418172

Only using git tags and ignoring the version in the package.json doesn't guarantee that the correct bundle is resolved if there are multiple bundles with the same version (specified in the package.json) matching the locked version. (This should not happen in my opinion as the lockfile saves a specific link, but does. Maybe because of some weird caching?)
I described the problem here: https://github.com/PSPDFKit/react-native/issues/173#issue-412360086

@radazzouz @nickwinder 
The reason against a patch-version bumps for things like this (even if there were only new windows features) is not clear to me. Android and Ios shouldn't be affected by this anyways (because it is a new version). Furthermore you don't even need to add the tag `1.23.3` if you don't want ios/android users to reference that version. Bumping the version in the package.json and adding a git tag for windows would be enough.

Please mind that we are building a cross platform app with windows and ios. It is not too bad if we manage our own package.json version changes in a fork, but an unnecessary overhead in imo.

**Comment by nickwinder** [comment]
Thanks for your detailed explanation, it helps us understand the situation much better. I'll bring this back to the team so we can have a good discussion about versioning to see what actions we can take to mitigate these issues. 
Thanks again.

**Comment by radazzouz** [comment]
@leoek we just tagged and released `1.23.3`.

**Comment by nickwinder** [comment]
@leoek In addition to the above, we had a discussion about how to tackle the versioning issue when developing a cross-platform application.

We've taken your advice on board and from now on when we post a PR for a bugfix or feature, before merging we will rebase and increment the patch number. This is true for all platforms.
This action can be seen in https://github.com/PSPDFKit/react-native/pull/202 where the template for the PR will advise the user to follow the new process.

Thanks for taking the time to provide great feedback and I hope this helps your situation.

**Comment by leoek** [comment]
@nickwinder @radazzouz This looks very good and will decrease the overhead of updating the rn wrapper for me. Thank you!
