### ISSUE TITLE
[IOS] Calling addAnnotation can crash the whole app.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#194]
**Current:**
When I try to add an an annotation with `addAnnotation` before the pdfViewer is ready, pspdfkit crashes the app.

**Expected**
The promise returned by addAnnotation should faill with a useful error message

**Steps to reproduce**
1. Use rn component: 
```
const { path } = this.props;
<PSPDFKitView
            ref="pdfView"
            style={[styles.pdfView]}
            onAnnotationsChanged={this.handleAnnotationsChanged}
            {...platformProps[os]}
            document={path}
          />
```
2. call addAnnotation with any annotation after the document prop was set, but before it loaded the pdf. 
```
this.refs.pdfView.addAnnotation({
      v: 1,
      type: 'pspdfkit/note',
      bbox: [
        460.8377990722656,
        199.1999969482422,
        24,
        24
      ],
      id: '01D68YW75EABFDE6RQBCEW6YCJ',
      opacity: 1,
      pageIndex: 0,
      createdAt: '2019-03-18T18:51:35.086+01:00',
      updatedAt: '2019-03-18T18:51:38.317+01:00',
      name: '01D68YW75EABFDE6RQBCEW6YCJ',
      color: '#FFD83F',
      icon: 'comment',
      text: 'fghjfghjghj'
    })
```

version: 1.23.0

**Comment by radazzouz** [comment]
Hi @leoek !

I was unable to reproduce this issue in our Catalog sample project on the latest version on master.

It would help us a lot if you could send us a modified version of `Catalog.ios.js` where we could reliably reproduce this behavior.

Thanks for your collaboration.

**Comment by leoek** [comment]
Hi @radazzouz 

I ran into another issue where addAnnotation crashed the whole app.
Unfortunately our demo application is not updated to the latest pspdfkit version and ios at the moment. I will invite you to it and I'll try to update it asap. This way you should be able to reproduce the issues.

The new issue happens if:
1. The user navigates to the screen with the pdfviewer
2. annotations are added with addAnnotation
3. the user leaves the screen (the react component is unmounted)
4. The user navigates to the screen with the pdfviewer again (same document, if another document is loaded in the mean time, the issue does not appear)
5. annotations are added with addAnnotation resulting in the crash
(there are annotations with the same name, as the annotations in step 2)

Screenshot after the crash:
<img width="1674" alt="Screenshot 2019-04-02 at 19 11 21" src="https://user-images.githubusercontent.com/9424038/55422658-6dec0200-557c-11e9-95ff-7a87c65a34e7.png">

**Comment by radazzouz** [comment]
Thanks for the additional information, @leoek!

It would help a lot if you could could send us the full symbolicated stack trace in text format. See our documentation here for more details: https://pspdfkit.com/guides/ios/current/troubleshooting/bug-reporting/#crashes

In addition, you can set an exception breakpoint in Xcode so we can see where it crashes. This might help if the crash occurs in the React Native wrapper.

Once again, thank you!

**Comment by leoek** [comment]
@radazzouz Thanks for pointing me in the right direction for these logs. (I am not to familiar with xcode..)

I will look into that.

**Comment by leoek** [comment]
@radazzouz I have updated the demo application and invited you to the repository. It's probably better to keep this in a private repository because of demo license keys etc in there.

**Steps to reproduce**

General:

1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. install dependencies with yarn: `yarn`
3. copy the pspdfkit lib (demo version) into `ios/PSPDFKit` (we only track the `VERSION` file in the git repository)
4. open the xcode project in xcode and run the app on an ipad

Issue specific:

1. Click on "Go To PdfScreen"
2. Add some annotations
3. Click on the "Back" Button in the top left corner
4. Click on "Go To PdfScreen"
--> The app crashes while we try to add the saved annotations (probably because the pdf is not loaded yet. the download is there on purpose to simulate a slow storage or delay caused by downloading or decrypting the pdf on the flow which is common in our application)

Note 1: If there aren't any annotations added, the pdfscreen can be opened multiple times without issues
Note 2: In our application this seems to happen only in occasions were we open the same pdf multiple times and try to add annotations. If we open a different pdf each time, the app does not crash (even if annotations are added)

**Comment by radazzouz** [comment]
@leoek,

Thank you very much for the detailed steps to reproduce and for send us the sample project.

I was able to successfully reproduce this behavior in your sample project. This was a timing issue. You were adding annotations to an invalid document and we've added checks in #209 to prevent such crashes in the future.

I would recommend that you audit your sample project's code to make sure that you do not add or remove annotations for an unloaded or invalid document.

In the meantime, until the #209 is merge, you can use [RCTPSPDFKitView.m](https://github.com/PSPDFKit/react-native/blob/rad/document-validation-check/ios/RCTPSPDFKit/RCTPSPDFKitView.m) from that branch.

Please let me know if this fixes the crash for you.

Once again, thank you for your collaboration!

**Comment by leoek** [comment]
>I would recommend that you audit your sample project's code to make sure that you do not add or remove annotations for an unloaded or invalid document.
