### ISSUE TITLE
Api of onAnnotationsChanged is inconsistent

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#196]
**Current**
onAnnotationsChanged receives an event which has the properties `change` and `annotations`.

- On WIndows annotations is an object with one annotation.
- On IOS annotations is an array with one? annotation(s) object(s) inside.

**Expected**
the annotations property should be of the same shape on all platforms.

**Comment by leoek** [comment]
@nickwinder @radazzouz any progress?

**Comment by nickwinder** [comment]
@leoek Please see https://github.com/PSPDFKit/react-native/pull/224
