### ISSUE TITLE
[IOS] Adjusting the locale

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#205]
# Details

There seems to be an option to adjust the locale in the native ios lib. I would like to adjust the locale from the javascript configuration.
I wouldn't mind to set the locale globally as it doesn't change. (similar to the license.)

# Acceptance Criteria

If there is already an option to adjust the locale from js:
- [ ] document that possibillity in the [Readme](https://github.com/PSPDFKit/react-native/blob/master/README.md)

If there is currently no such an option:
- [ ] add an option to define a locale string from js or to supply an object with the translated strings, which override the default strings.

- [ ] document how it is used in the [Readme](https://github.com/PSPDFKit/react-native/blob/master/README.md)

# Additional Information

I changed the language on the ios device to german. All native ios components (outside of react-native-pspdfkit) were translated by default, if there was no custom label defined.

**Comment by radazzouz** [comment]
@leoek,

You can manually override the system defaults and force a specific language. We generally do not recommend this as it's against Apple HIG and the platform handles this system-wide very well. So I'll be closing this issue.

That said, if you absolutely want to manually override the default locale, you can do so early in your app delegate in native code (Objective-C). We wrote about how to do customizations in Objective-C in here: https://pspdfkit.com/blog/2018/how-to-extend-react-native-api/#customizing-the-ui-using-native-code

Here's how manually override localization iOS in Objective-C: https://pspdfkit.com/guides/ios/current/features/localization/#manually-override-localization

Please let me know if this helps you accomplish your use case.

Thanks!

**Comment by leoek** [comment]
@radazzouz Please reopen the issue.

I would be very happy if pspdfkit would just use the systems language to display its labels. However pspdfkit is not doing that, which is why I was looking for a way to supply the correct locale or supply a configuration with the strings to override the strings with the wrong language.

<img width="866" alt="Screenshot 2019-04-04 at 12 04 26" src="https://user-images.githubusercontent.com/9424038/55547667-0fd13300-56d2-11e9-8dd8-d0fc61f7e5e6.png">
<img width="861" alt="Screenshot 2019-04-04 at 12 05 03" src="https://user-images.githubusercontent.com/9424038/55547687-13fd5080-56d2-11e9-9709-a751da52b741.png">

**Comment by steipete** [comment]
Leonard, first of all: thanks for your contributions here!

I've reopened the issue, but it's a curious one. We don't even allow setting a custom language on iOS - the app always uses the system language:

https://pspdfkit.com/guides/ios/current/features/localization/

This does require localization bundles for e.g. german in your app. Could it be that this is missing?

You can use an iOS hack to force the language, but that's not recommended.
https://pspdfkit.com/guides/ios/current/features/localization/#manually-override-localization

Please attach lldb to your app and send me the output of `NSBundle.mainBundle.preferredLocalizations.firstObject` (you might need a few more square brackets instead of dots to satisfy lldb)

This is the code we use to figure out what locale to load.

**Comment by leoek** [comment]
@steipete Currently we have only one language, which is german and therefore no localization enabled. (We don't have any native ios components which we would need to translate anyways.)

Could you elaborate on how I get that output from lldb? (I am not too familiar with xcode..)

**Comment by leoek** [comment]
@steipete I think I found the issue. There was "English - Deprecated" as language in the localization seconds of xcode which seemed to cause the issue. Since I removed that, the strings in pspdfkit appear correctly in german.

**Comment by radazzouz** [comment]
Awesome! Thanks for letting us know that you've got it sorted out, @leoek!
