### ISSUE TITLE
Back button in Android

### ISSUE THREAD

**Issue by tponte** [PSPDFKit/react-native#206]
# Details
In Android, opening a document using PSPDFKit.present doesn't show a back button 

# Acceptance Criteria
Back button should return to the RN app.

**Comment by irgendeinich** [comment]
@tponte 
We recently merged a couple or PRs that now make this possible when using the `PSPDFKitView`. 
See https://github.com/PSPDFKit/react-native/releases/tag/1.27.2 and https://github.com/PSPDFKit/react-native/releases/tag/1.27.0

I'm going to close this issue, should this not solve your issue feel free to reopen this issue.
