### ISSUE TITLE
[UWP] Promise of first setToolbarItems call is never resolved nor rejected

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#207]
# Details

If I call setToolbarItems for the first time, the returned promise is never rejected nor resolved. This only happens for the very first time only. (after restarting the whole app, reloading js doesn't trigger this behavior)

I can see that the call was successful by the change of the toolbaritems.

windows sdk 1.11
wrapper: 1.23.2

# Acceptance Criteria

- [x] The promise returned by the first call to setToolbarItems should resolve as the ones from later calls.

**Comment by nickwinder** [comment]
@leoek Thanks for reporting this! 
I've found the issue and have posted a PR for review. Keep an eye of this ticket and we'll get the fix in soon.
