### ISSUE TITLE
[UWP] Dates of Annotations added with addAnnotation are reset

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#213]
# Details

**Current**
If an annotation is added with `addAnnotation(<annotation>)` the dates in that annotation object are reset to the current date and time.

**Expected**
Annotations added with `addAnnotation` should keep the dates from the annotation object.

Example:

After adding the following annotation

`{"v":1,"type":"pspdfkit/note","bbox":[404.8377380371094,40.79999923706055,24,24],"id":"01D8K898PQXEGPG9TDDG5FANXW","opacity":1,"pageIndex":0,"createdAt":"2019-04-16T16:19:47.799+02:00","updatedAt":"2019-04-16T16:21:18.279+02:00","name":"01D8K7KWHSTRGGXFVQ16311EV8","color":"#FFD83F","icon":"comment","text":"16.04.2019"}`

the date in the left bar is shown as 17th of april (today) altoguh the annotation object contains dates with 16th of april.

# Acceptance Criteria

- [ ] `addAnnotation` adds annotations as they are and does not modify dates or times

**Comment by nickwinder** [comment]
Previously this was not a field that was permitted for the user to define, but after reviewing this we've decided that there should be no reason to restrict this.

In subsequent releases of PSPDFKit for Windows we've decided to change this and therefore fixing this issue. The fix has to come through the SDK and go through QA so I will leave this issue open until we see it in the react-native wrapper.

**Comment by leoek** [comment]
@nickwinder 

Do you have a timeline for the sdk change and QA?

**Comment by nickwinder** [comment]
QA permitting, we are looking at a release date towards the end of next week.

**Comment by leoek** [comment]
@nickwinder was this part of 1.23.11?

**Comment by nickwinder** [comment]
No, this is part of https://github.com/PSPDFKit/react-native/pull/223 which is just making it's way through now.

**Comment by nickwinder** [comment]
Fixed with https://github.com/PSPDFKit/react-native/pull/223
