### ISSUE TITLE
Custom CSS colors crash in production

### ISSUE THREAD

**Issue by nickwinder** [PSPDFKit/react-native#219]
# Details
Custom CSS colors work completely fine when debugging the application, but with a production build, it crashes. 

# Reproduce
- Follow instructions https://github.com/PSPDFKit/react-native#running-catalog-project-2
- Click on the Custom CSS colors list item. 
- Observer crash.

It is assumed that there is a file writing issue due to windows file permissions.

# Acceptance Criteria

- [ ] Catalog does not crash in production mode when running the Custom CSS example.

**Comment by nickwinder** [comment]
@leoek 
I'm afraid to say this issue falls down to a limitation of file handling with a UWP Webview. It's a common problem with UWP due to the strict file permissions enforced on the applications. 

This means that the current solution is not going to work and a workaround will have to come as part of a small amount of native work (adding a file and a call in the visual studio project) in the user's (of `react-native-pspdfkit`) project. I will remove the Custom CSS API that was created and replace the catalog example with the workaround in which you can follow for a complete solution.

**Comment by leoek** [comment]
@nickwinder I welcome a native solution, but could elaborate a bit more on the issue? What is the connection between a css color and limitations of file handling?

**Comment by nickwinder** [comment]
@leoek 
Absolutely. As you can see from https://github.com/PSPDFKit/react-native/blob/fec925dcc83aeba9fe25e3658644d55cb1fe5629/windows/ReactNativePSPDFKit/ReactNativePSPDFKit/PSPDFKitViewManager.cs#L63-L105 we were creating a css file that can be passed to the PSPDFKit for Windows framework.
This file would subsequently be passed to a `Webview` which drives the PSPDFKit for Windows framework. But because of file limitations within UWP, you cannot simply pass a file from a local path to the `WebView` to `fetch`, it has to be a file within the web context which is what https://docs.microsoft.com/en-us/windows/uwp/app-resources/uri-schemes#ms-appx-and-ms-appx-web explains. The issue here is that the files accessible from the web context is only from the install folder. In production mode, it is not possible to write or move into the install folder for security reasons (which is understandable). This is why previously it was working when debugging but not when deploying. 
I hope this is understandable and just ask if you need any other clarification.

**Comment by leoek** [comment]
@nickwinder I understand the issue now. But is it really necessary to write these colors into a css file. It should be possible to pass them to the library like everything else (annotations, toolbar items, etc) or am I missing something?

**Comment by nickwinder** [comment]
@leoek It would technically be possible to pass said colors all the way through from react-native -> Windows UWP -> WebView (PSPDFKit for Web) and then merge these values with any styling already applied, but this is not currently supported in PSPDFKit for Web and will not be supported for the foreseeable future. Therefore the solution I have offered is the only one I can offer in a timely fashion to satisfy your needs.

**Comment by leoek** [comment]
@nickwinder thanks for the fix. Unfortunately this can only be temporary for us.

Our app can have dynamic themes. Therefore we would need a method which does not require them to be a statically linked resource.

**Comment by nickwinder** [comment]
@leoek 
Understood. Would it be possible for you to create a new issue with your exact requirements to ensure that this request is not lost? 
Thanks
