### ISSUE TITLE
[Android] pageMode is ignored

### ISSUE THREAD

**Issue by ViktorFowl** [PSPDFKit/react-native#225]
# Details
When passing configuration details to `PSPDFKitView`, specifically `pageMode="single"` this configuration is ignored. Is it not implemented on Android or is there some issue?

# Acceptance Criteria
Can configure `PSPDFKitView` to display a pdf as a single page.

**Comment by irgendeinich** [comment]
Hey,
I went ahead and created a PR adding the missing configuration options to our Android wrapper you can find it here https://github.com/PSPDFKit/react-native/pull/227.

Once this is approved and merged you just need to update your used PSPDFKit wrapper version and it should work.

**Comment by ViktorFowl** [comment]
Thank you, I am new to this lib, we are implementing it in our project. I checked your changes and I hope I will be able to help with PRs when I get to know this lib better.
