### ISSUE TITLE
Looking for proptypes

### ISSUE THREAD

**Issue by maheshgajadhar** [PSPDFKit/react-native#231]
Hi, 

The link for all the prop types for PSPDFKitView is not working anymore, where can i find them ?

**For all the props that you can pass to PSPDFKitView, have a look at the source documentation**

**Comment by radazzouz** [comment]
Thanks for reporting this, @maheshgajadhar!

PR #232 fixes the broken link.

In the meantime, here's where you can find the prop types: https://github.com/PSPDFKit/react-native/blob/master/index.js
