### ISSUE TITLE
[Android] Native UI Component does not render anything.

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#237]
# Details

**Current**
The PSPDFKitView Component does not render anything on Android.

**Expected**
The PdfView is rendered in the view hierarchy as it is on ios.

**Additional Information**

tested with react-native-pspdfkit version: 1.24.2 and 1.23.7

We tried to use paths formatted like this: `/data/user/0/com.appname/files/tmp/dokument/7_0` and `file:///data/user/0/com.appname/files/tmp/dokument/7_0`

We are using `ReactFragmentActivity` as documented in the Readme.
```
import com.facebook.react.ReactFragmentActivity;

public class MainActivity extends ReactFragmentActivity {
    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "my-appname";
    }
}
```

# Acceptance Criteria

- [ ] PSPDFKitView renders the pdf supplied through the `document prop`
- [ ] If the value of the `document` prop changes, the new pdf will be rendered.

**Comment by irgendeinich** [comment]
Hey, I tried reproducing this in our catalog sample app, but pointing it to different files always worked.
* External Documents worked - `"file:///sdcard/Annual Report.pdf"`
* Internal Documents worked - `"file:///data/user/0/com.pspdfkit.react.catalog/files/Annual Report.pdf"`
* Asset Documents worked - `"file:///android_asset/Annual Report.pdf"`

We already check inside the `ReactPdfViewManager` that the activity subclasses `ReactFragmentActivity` so that shouldn't be the issue either.

Are you using the same JavaScript for iOS and Android? Could you share a small runnable example exhibiting this issue, or a modification made to the Catalog that shows the same error?

**Comment by leoek** [comment]
@irgendeinich yes we have one shared component for android, ios and windows. I'll check whether we can update our demo application for android in a reasonable timeframe.

**Comment by leoek** [comment]
@irgendeinich 

We updated our demo application to support android. The steps to reproduce the issue are the following:

1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. checkout reproduce-isssue-237_native-ui-comp-not-rendering
3. `yarn`
4. `yarn android`
5. Press "Go To PdfScreen"
--> There should be this message (from within the render function) in the log now 
```
["pdf"] "render pdfview" "/data/user/0/com.pspdfkitdemo/files/sitzungsunterlage_0_0"
```
--> **Current**: no pdf is rendered
--> **Expected**: PdfViewer with loremipsum pdf is rendered

6. Click on "Back" in the top left
7. Click on "Go To PdfScreen"

--> **Current**: The App will crash with the following stacktrace:
```
➜ adb logcat -s System.err:* om-pspdfkitdem:*
--------- beginning of main
--------- beginning of system
07-02 15:04:32.934  6107  6107 W System.err: io.reactivex.exceptions.OnErrorNotImplementedException: Error while loading PdfDocument
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:47)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
07-02 15:04:32.934  6107  6107 W System.err:    at android.os.Handler.handleCallback(Handler.java:873)
07-02 15:04:32.934  6107  6107 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
07-02 15:04:32.934  6107  6107 W System.err:    at android.os.Looper.loop(Looper.java:193)
07-02 15:04:32.934  6107  6107 W System.err:    at android.app.ActivityThread.main(ActivityThread.java:6669)
07-02 15:04:32.934  6107  6107 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-02 15:04:32.934  6107  6107 W System.err:    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-02 15:04:32.934  6107  6107 W System.err:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-02 15:04:32.934  6107  6107 W System.err: Caused by: java.io.IOException: Error while loading PdfDocument
07-02 15:04:32.934  6107  6107 W System.err:    at com.pspdfkit.framework.fz.p(SourceFile:432)
07-02 15:04:32.934  6107  6107 W System.err:    at com.pspdfkit.framework.fz.<init>(SourceFile:333)
07-02 15:04:32.934  6107  6107 W System.err:    at com.pspdfkit.framework.fz.a(SourceFile:124)
07-02 15:04:32.934  6107  6107 W System.err:    at com.pspdfkit.framework.da$1.call(SourceFile:1059)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.Single.subscribe(Single.java:3394)
07-02 15:04:32.934  6107  6107 W System.err:    at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
07-02 15:04:32.935  6107  6107 W System.err:    at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:579)
07-02 15:04:32.935  6107  6107 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
07-02 15:04:32.935  6107  6107 W System.err:    at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
07-02 15:04:32.935  6107  6107 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
07-02 15:04:32.935  6107  6107 W System.err:    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
07-02 15:04:32.935  6107  6107 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-02 15:04:32.935  6107  6107 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-02 15:04:32.935  6107  6107 W System.err:    at java.lang.Thread.run(Thread.java:764)
07-02 15:04:32.935  6107  6107 W System.err: Caused by: java.lang.RuntimeException: File not found or could not be opened. (errno:2, file://data/user/0/com.pspdfkitdemo/files/sitzungsunterlage_0_0)
07-02 15:04:32.935  6107  6107 W System.err:    at com.pspdfkit.framework.jni.NativeDocument.open(Native Method)
07-02 15:04:32.935  6107  6107 W System.err:    at com.pspdfkit.framework.fz.p(SourceFile:419)
07-02 15:04:32.935  6107  6107 W System.err:    ... 16 more
```
--> **Expected**: PdfViewer with loremipsum pdf is rendered

**Comment by leoek** [comment]
Opening the same file with `present(<path>, <config>) works.

**Comment by irgendeinich** [comment]
@leoek 
Thanks for providing the sample project. I found a couple of things that need changing for it to work. 

1. In the example the `PSPDFKitView` has no configuration. It needs one even if it is just `{}` otherwise nothing will be rendered, this is probably not ideal. I'll change it so we automatically use a default configuration instead of silently failing.
2. Our wrapper isn't quite happy with the file path in the example. I'll make it handle this more gracefully.
3. Setting a document and then resetting it to null causes a crash. I'll fix this issue as well.

I'll update this issue as soon as we have a fix for the issues.

**Comment by leoek** [comment]
@irgendeinich Thanks for the fast feedback.

>In the example the PSPDFKitView has no configuration. It needs one even if it is just {} otherwise nothing will be rendered, this is probably not ideal. I'll change it so we automatically use a default configuration instead of silently failing.

**Comment by irgendeinich** [comment]
> How do we need to change our file path? Should we prefix it with file://?

Yes if you passed in `file:///data/user/0/com.pspdfkitdemo/files/sitzungsunterlage_0_0` it should work. Note the three slashes at the beginning.

> We should be able to work around this by supplying a configuration until this is handled, correct?

Yes, setting:

```
configuration: {}
```

made it work when I ran the example.

**Comment by Elmatoss** [comment]
> Yes if you passed in file:///data/user/0/com.pspdfkitdemo/files/sitzungsunterlage_0_0 it should work. Note the three slashes at the beginning.

If I pass the path on to the `document` prop like that, the app keeps stopping

Setting configuration makes the pdfscreen work, but no Toolbar is displayed.. See https://github.com/PSPDFKit/react-native/issues/245

**Comment by Andrea-Arguello** [comment]
I am experiencing this issue on branch 1.24.0. We have a configuration sent to the component, and I have tried sending the path both as @Elmatoss and with ```file://``` preceding it. However, it is still coming up blank.

**Comment by leoek** [comment]
@Andrea-Arguello Did you try it with `file://` or `file:///`. (It only works if you have 3 slashes.)

**Comment by Andrea-Arguello** [comment]
I have tried with ```file:///```, and it does not crash but it still doesn't render.
I have created a repository replicating the issue, since I am currently unable to upgrade to another tag until Expo upgrades to RN 0.60.x:
https://github.com/cluis13915/pspdfkit-1-24-0-android-issue
