### ISSUE TITLE
[UWP] System.OutOfMemoryException

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#239]
# Details

After opening a few pdfs with some annotations I get a "System.OutOfMemoryException" Exception. The Exception is thrown in the last line of this snippet from WebSocketJavaScriptExecutor.cs:

```
        private void OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args)
        {
            using (var reader = args.GetDataReader())
            {
                reader.UnicodeEncoding = UnicodeEncoding.Utf8;
                var response = reader.ReadString(reader.UnconsumedBufferLength);

                var json = JObject.Parse(response);
```

System.OutOfMemoryException: Exception_WasThrown    bei Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(Boolean append, Int32 charsRequired)    bei Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)    bei Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)    bei Newtonsoft.Json.JsonTextReader.ParseValue()    bei Newtonsoft.Json.JsonTextReader.Read()    bei Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)    bei Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)    bei Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)    bei Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)    bei Newtonsoft.Json.Linq.JObject.Parse(String json)    bei ReactNative.DevSupport.WebSocketJavaScriptExecutor.OnMessageReceived(MessageWebSocket sender, MessageWebSocketMessageReceivedEventArgs args) in C:\projects\insession\node_modules\react-native-windows\ReactWindows\ReactNative\DevSupport\WebSocketJavaScriptExecutor.cs: Zeile283} | System.OutOfMemoryException

# Acceptance Criteria

- [ ] Opening (multiple) pdfs with annotations does not result in Exceptions

**Comment by nickwinder** [comment]
@leoek Thanks for the report. 
I'd love to get a little more info on the issue, so we can reproduce the issue.

Do you have any example documents/PDFs that you are using. Feel free to host elsewhere and open an issue on Zendesk if these should be remain private. 

Are you opening the documents in the single `PDFView` one after the other? Or is this multiple instances of the `PDFView` in a single application? 

Does this happen when the `present` method is called or at another time?

**Comment by leoek** [comment]
@nickwinder 

I am not sure whether this is a single instance or not. We have one Component which contains a single `<PSPDFKitView />`. While the user is on the Screen with that component we call `present(<path>)` once.

In the past we did not call `present` again when the user entered that Screen again and had still the same Pdf selected. If the user had another pdf selected and entered that Screen again, we called `present(<newpath>)` with the new path and displayed an overlay over the Screen until the new Pdf was loaded. (Because previous versions were not clearing their state, if the `<PSPDFKitView />` was unmounted. Therefore the old pdf would still be displayed on the next mount of `<PSPDFKitView />`)

Now with 1.24.3 and windows 2.2 we call `present(<newpath>)` every time the user enters the Screen which contains the `<PSPDFKitView />`. (Pspdfkit does not keep it's state any more if the `<PSPDFKitView />` is unmounted.)

**Comment by nickwinder** [comment]
> I need to check this. Could happen during the annotation import too. 

This will help us track it down. I'll wait for that info. Thanks

**Comment by leoek** [comment]
@nickwinder We observed the bug now in situations where we opened a pdf without annotations and were not adding annotations though the ui nor the api.

**Comment by nickwinder** [comment]
@leoek So I think I may have something which I'm going to file internally and may be what you are hitting. It's fairly hard to correlate though. 

I believe it's actually a x86 build issue. Therefore, if you jump to your project in VS and use x64 to run the project instead I think you will not get the same crashes. 

Is there any chance you could try this to confirm?

**Comment by leoek** [comment]
@nickwinder I think I have identified the main issue we had as a memory leak in Newtonsoft.

About x86/x64:

We were running x64 when we observed the issue although the packages which we ship are x86 and x64. Memory seems to be stable with x64 after applying #249 .

**Comment by nickwinder** [comment]
I'm closing this as it seemed to be down to Newtonsoft. The downgrade has been applied.
