### ISSUE TITLE
[Android] Native UI Component does not render the Toolbar

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#245]
# Details

### Current
The PSPDFKitView Component does not render the Toolbar on Android.

### Expected
The Toolbar is rendered in the PSPDFView Component 

### Additional Information
See https://github.com/PSPDFKit/react-native/issues/237
--> configuration prop is passed on to PDFView

1. clone https://github.com/leoek/react-native-pspdfkit-demo
2. checkout reproduce-isssue-237_native-ui-comp-not-rendering
3. yarn
4. yarn android
5. Press "Go To PdfScreen" 
--> No Toolbar is displayed

# Acceptance Criteria

- [ ] Toolbar is rendered in the PSPDFKitView when using the Native UI Component

**Comment by irgendeinich** [comment]
Thanks for providing the runnable example.

This is actually the intended behaviour, the toolbar is not part of the `PSPDFKitView` unlike on iOS. This is due to the fact that it is part of the `PdfActivity` UI and not the `PdfFragment` UI. 

The toolbars for creating and editing annotation do still work though.

**Comment by Elmatoss** [comment]
Alright, then how exactly do I add the toolbar when using the Native UI Component?

**Comment by irgendeinich** [comment]
All you need to provide is a view that allows users to enter and exit the annotation creation mode using `enterAnnotationCreationMode`.

All other options normally found on the toolbar (outline, search, view settings, sharing and thumbnail grid) sadly aren't supported by the `PSPDFKitView` on Android right now.

**Comment by leoek** [comment]
@irgendeinich we definitely need search and view settings. How can we get them?

**Comment by irgendeinich** [comment]
For the view settings you could build the view settings UI yourself using a custom react-native UI. All this view would need to do is display the current `configuration` and update it according to user input. This should already be possible with the currently exposed API.

As for the search, it might be possible to expose the the internal search API in react-native so you can build your own search UI on top of that, but I can't make in promises in that regard.

In any case I'll bring up both points with the rest of the team for further discussion as adding them to our react-native wrapper would be a longer project.

**Comment by leoek** [comment]
@irgendeinich I started building the described workaround but got stuck with `enterAnnotationCreationMode` #247

**Comment by irgendeinich** [comment]
An update on this issue, we shipped the `PdfUiFragment` with 6.0 of PSPDFKit. The `PdfUiFragment` provides the complete `PdfActivity` UI in a fragment, we will integrate this into the wrapper, then you'll have access to all toolbars the same as on iOS.
