### ISSUE TITLE
expo 

### ISSUE THREAD

**Issue by flieks** [PSPDFKit/react-native#25]
Are there plans to support expo sdk ?

**Comment by radazzouz** [comment]
@flieks you mean https://expo.io?

If so, does it require a different wrapper? Have you tried using the current React Native module in your app?

**Comment by flieks** [comment]
Hi Rad,
Yes expo.io. Well, i did detach because the pdf additional steps (adding the maven in build.gradle) isn't possible in expo without detaching. 
But detaching has disadvantage that i can't use the expo push notifications sdk (client and server sdk) anymore.
With supported, i think it means you can be included in the expo SDK. Other 3th party support in their now is Segment, Amplitude, Facebook, FacebookAds, Lottie, GLView (threejs). But nothing exists for PDF yet. The free pdf libs don't work because it uses rnfs (in rn-fetch-blob) which contains a bug. 
Expo's document Picker gives back a content:// url which seem to work with pspdfKit.

**Comment by steipete** [comment]
Thanks for the ping! I've read about [detaching](https://docs.expo.io/versions/latest/guides/detach.html) from ExpoKit.

This is the first time I've personally heard about Expo, but we'll keep an eye on popularity and explore a deeper integration if this project gains more traction. From a first look it seems very non-trivial, especially as our Android-setup requires a native library and a few dependencies.

Push Notification seems to be a current restriction of Expo that surely can be solved by them, as it's just about certificates. We recommend [Firebase Cloud Messaging](https://firebase.google.com/docs/cloud-messaging/) as a solid, cross-platform push notification pipeline service, if you don't want to maintain your own (which isn't very hard either, there's good open source libraries available that solve that really well)

Our next project is to bring our sync engine PSPDFKit Instant over to React Native:
https://pspdfkit.com/instant/

Thanks for the feedback! Pull Requests are welcome.

**Comment by kay-is** [comment]
@flieks does this work with documents that aren't accesible for other apps?

**Comment by flieks** [comment]
@kay-is i don't know. I went back to using webview (and custom pdfViewer implementation in java for android)

**Comment by kay-is** [comment]
@flieks ah, okay. how do you annotate in a webview?
