### ISSUE TITLE
[Android] Native UI Component only reads configuration on mount

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#252]
# Details

Current:

The native UI Component only reads it's configuration when mounted. If something is changed afterwards (for example the property `showThumbnailBar`) the change is not applied until the component is unmounted and mounted again.

Expected:

The native UI Component should read and apply it's configuration on every render. (React Components should usually rerender if their props change)

I am building our own toolbar because of #245 and I currently need to remount our whole PdfView on every configuration change (Basically every click in our toolbar...).

# Acceptance Criteria

- [ ] Changes of the props of `PSPDFKitView` are applied immediately (especially configuration changes).

**Comment by leoek** [comment]
@irgendeinich I just upgraded to the version 1.24.9 and the issue is still there.

My configuration did change and my parent component of PSPDFKitView did rerender, however the the new configuration was not applied by pspdfkit.

(I changed showThumbnailBar from "none" to "scrollable")

**Comment by leoek** [comment]
@irgendeinich It works now, but there is still an issue with thumbnailtoolbar. It is now rendered above the pdf if the toolbar is activated after the first render.

![2019-08-07-210526_571x563_scrot](https://user-images.githubusercontent.com/9424038/62650485-45737a80-b957-11e9-8df7-f8e8a260a597.png)

**Comment by leoek** [comment]
Expected:
![2019-08-07-210711_636x424_scrot](https://user-images.githubusercontent.com/9424038/62650516-59b77780-b957-11e9-9756-5931bb27e75d.png)

**Comment by irgendeinich** [comment]
@leoek 
I tried to reproduce your issue, but I didn't manage. I started my configuration out with `showThumbnailBar : "none"` and then when pressing a button replaced it with `showThumbnailBar : "scrollable"` but it is working as intended.
![thumbnail_bug](https://user-images.githubusercontent.com/2066444/62713306-cdf82680-b9fc-11e9-9175-9870f669b43f.gif)

Could you create a new issue with specific reproductions steps so I can take a look?
