### ISSUE TITLE
[iOS] Configurable documentLabel

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#253]
# Details

This is a follow-up on #220 and #233 as advised in [this comment](https://github.com/PSPDFKit/react-native/issues/220#issuecomment-499628127)

Currently there is an option to configure whether the documentLabel should be shown in the toolbar or not. This helps to avoid meaningless titles or filenames being displayed.
However it would be great if the app could supply a string to the `PSPDFKitView` with a custom documentLabel as it may have more context to the pdf.

We currently display a custom title above the `PSPDFKitView` which works fine but uses valuable additional screen space.

# Acceptance Criteria

- [ ] `PSPDFKitView` or it's configuration has a property in which a string can be supplied which is rendered as documentLabel. (This would override the title whcih can be obtained from within the pdf)

**Comment by radazzouz** [comment]
@leoek Thanks for creating a followup issue per https://github.com/PSPDFKit/react-native/issues/220#issuecomment-499628127.

How is this issue related to #233?

Thanks!

**Comment by leoek** [comment]
@radazzouz #233 was the pull request which introduced the `showDocumentLabel` option.

**Comment by radazzouz** [comment]
> @radazzouz #233 was the pull request which introduced the `showDocumentLabel` option.

In #233, we added Javascript API to customize the toolbar buttons on iOS. The only change related to `showDocumentLabel` was a fixing a small code format issue in https://github.com/PSPDFKit/react-native/pull/233/files#diff-c242db1b34aac23f8a3a7c48ccc0085cR98.


`showDocumentLabel` is a React Native configuration property which maps to the native iOS `documentLabelEnabled` property, and this was done in #159.

Note that neither pull requests (#233 or #159) impact this enhancement request.

Thanks!

**Comment by radazzouz** [comment]
https://github.com/PSPDFKit/react-native/pull/255 adds the ability to override the toolbar title.

**Note:** You need to set `showDocumentLabel`, `useParentNavigationBar`, and `allowToolbarTitleChange` to false in your Configuration **before** setting the custom title. See the updated version of `ConfiguredPDFViewComponent`.

**Comment by leoek** [comment]
@radazzouz Thanks for the clarification! I must have confused things with #233 

> #255 adds the ability to override the toolbar title.
Thanks this sounds great! I will check this out asap.

**Comment by radazzouz** [comment]
Implemented in #255. Closing this issue.
