### ISSUE TITLE
export

### ISSUE THREAD

**Issue by flieks** [PSPDFKit/react-native#26]
Is there an export function in pspdfKit.

Problem i'm facing. I'm getting a content:// url from document picker from expo sdk. 
I want to upload with formData but it didn't work with content://. Maybe file:// works

**Comment by steipete** [comment]
PSPDFKit saves data automatically, there should not be any need to export a file:
https://pspdfkit.com/guides/ios/current/annotations/annotation-saving-mechanism/

For further questions please ping us on our support ticket platform:
https://pspdfkit.com/support/request

Thanks!
