### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by flieks** [PSPDFKit/react-native#27]
Are all configuration settings of https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html supported to give to PSPDFKit.present() ? 
Which other PSPDFKit events and functions are supported in this library ? 
For example: to hook into document events like page click event, or search for text and scroll to that page..
Thanks

**Comment by steipete** [comment]
We tried to keep the React Native bindings for PSPDFKit very simple. We made them open source so everyone can extend them as needed. See here for an example how to build a non-modal presentation: https://pspdfkit.com/blog/2017/native-view-controllers-and-react-native/

Our next project is to bring our sync engine PSPDFKit Instant over to React Native:
https://pspdfkit.com/instant/

Once that is done we'll explore ways to further improve the bindings here. We support a large set of bindings, from Appcelerator to Xamarin, even PhoneGap - so there's a lot of work happing to keep everything up top date.

If you require specific events like the [page tap handler](https://pspdfkit.com/api/ios/Protocols/PSPDFViewControllerDelegate.html#/c:objc(pl)PSPDFViewControllerDelegate(im)pdfViewController:didTapOnPageView:atPoint:), feel free to send a Pull Request - thanks!
