### ISSUE TITLE
"null is not an object" error 

### ISSUE THREAD

**Issue by Andrea-Arguello** [PSPDFKit/react-native#270]
# Details
I am wondering if this is an incompatibility issue with regards to the React Native version the project is on.
I am working with Expo, which currently supports RN 0.59.8, which is behind the PSPDFKit required version.
I have tried for the past few days to use both the Native UI Component as well as PSPDFKit.present, but both throw a "null is not an object (evaluating PSPDFKit.present/setLicenseKey)." I also check previously if the device running is iOS or Android, and load the respective LicenseKey.

Any help would be welcome at this point, as I have followed throughout the documentation (especifically the Android setup), and I am not able to fix this. Could this be because of the requirement for the latest RN version?

**Comment by radazzouz** [comment]
@Andrea-Arguello,

React Native changed a lot since version 0.59.8, and we made a lot of changes in our wrapper (on both Android and iOS) to be compatible with the latest version of React Native. 

I am sorry that we don't support older versions of React Native or Expo.

It's hard to tell if the problem is caused by the older version of React Native or Expo itself. 

I suspect that Expo need to make some changes too in order to support the latest version of React Native.

Assuming Expo is a hard requirement, that I would suggest that you wait for it (Expo) to support React Native 0.60.x or later.

I would also recommend that you use our wrapper as-is without using Expo.

I hope that this helps.

**Comment by radazzouz** [comment]
@Andrea-Arguello,

As a third solution, you can also try to checkout an older tag (like [1.24.6](https://github.com/PSPDFKit/react-native/releases/tag/1.24.6) which requires RN 0.59.9) to use an older version of our wrapper which requires a React Native version earlier than 0.60.x. 

If you decide to try this solution, please make sure that you make sure that your check all the requirements for both iOS and Android in the REAME.

Let me know if this helps you.

**Comment by Andrea-Arguello** [comment]
Hi, I haven't been able to solve this issue. However, it did catch my attention (and I'm speculating that this is the problem) that PSPDFKit is not being added to de MainActivity.java of the Android app after manually linking AND using react-native link to link the library.

**Comment by irgendeinich** [comment]
@Andrea-Arguello 
It isn't quite clear from the info you provided if you are using Expo or ExpoKit?

I checked the Expo documentation and apparently native modules are only supported if you eject your project and use ExpoKit. See [here](https://docs.expo.io/versions/latest/introduction/faq/#how-do-i-add-custom-native-code) and [here](https://docs.expo.io/versions/latest/expokit/overview/)

**Comment by Andrea-Arguello** [comment]
It was ejected to ExpoKit

**Comment by irgendeinich** [comment]
I tried to reproduce this, but sadly failed.
I created a new project using `expo init` and the managed workflow. Immediately ejected it and added our wrapper.
Using `react-native link react-native-pspdfkit` did work as expected, updating `settings.gradle` and `MainApplication.java` with the necessary changes for the native-module.

If you could send over an example project exhibiting this issue that would be useful.

**Comment by Andrea-Arguello** [comment]
I will try again, and verify that the project is indeed ejected and either the latest RN version or the 1.24.6 tag.

**Comment by Andrea-Arguello** [comment]
Closed this issue because as suggested by radazzous(https://github.com/PSPDFKit/react-native/issues/270#issuecomment-521259267), we opted to use tag 1.24.0 as this supports RN 0.59.8. However, #274 arose.

**Comment by radazzouz** [comment]
Thanks for the context @Andrea-Arguello! 

We also received your support request 15295 in our support platform (pspdfkit.com/support/request/) and we will follow up in there. We will also update #274 if needed.
