### ISSUE TITLE
Manifest merger fails after running react-native link

### ISSUE THREAD

**Issue by Andrea-Arguello** [PSPDFKit/react-native#271]
# Details
This error hadn't happened to me before, but now, after running react-native link react-native-pspdfkit I get the following error message as I try to build the app.
```
> Manifest merger failed : Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.1] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:48:3-371:17 to override.
```

# Other information
Currently, I have this calls to the com.android.support imlementatio:

```
// android/app/build.gradle
implementation "com.android.support:exifinterface:${safeExtGet("supportLibVersion", "28.0.0")}"
androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'


androidTestImplementation 'com.android.support.test:runner:1.0.1'
androidTestImplementation "com.android.support:support-annotations:${safeExtGet("supportLibVersion", "28.0.0")}"
androidTestImplementation 'com.android.support.test.uiautomator:uiautomator-v18:2.1.1'

// layout .xml uses the component
<android.support.v4.view.ViewPager ... />
```

What fixes may I try for this? I have tried a lot of stackoverflow answers, but it seems as if the trouble was between the project and the library's manifest, as this problem is recent and hadn't happened to me before.

**Comment by quarryman** [comment]
Looks like a collision of android.support and androidX which can not leave in pace together.
Are you using androidX or android.support in your app?

**Comment by Andrea-Arguello** [comment]
android.support. However, this error only shows up after doing the linking between react and the dependency

**Comment by Andrea-Arguello** [comment]
Closing as this issue does not appear after using tag 1.24.0. However, the problem described in issue #274  arose.
