### ISSUE TITLE
[IOS] timestamps which are not in zulu time are handled incorrectly

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#279]
# Details

If annotations with timestamps which are not in zulu time are imported to pspdfkit ios, it will parse the time incorrectly.

react-native-pspdfkit: 1.24.9
pspdfkit for ios: 8.4.1

**Example**

1. Annotation was created on Windows 13:47 MESZ (GMT +2)
2. IOS shows 15:47 as the creation time which is still in the future

![Screenshot 2019-08-27 at 13 54 33](https://user-images.githubusercontent.com/9424038/63769165-62ee9100-c8d2-11e9-8960-9541b9aaedd1.png)

**Steps To Reproduce**

1. Create an annotation with react-native-windows
2. Export the instant json from the uwp app
3. import the instant json to an ios app

alternatively to step 1 & 2 use the following annotation
```
{
    v: 1,
    type: 'pspdfkit/note',
    bbox: [
      500.8377990722656,
      112,
      24,
      24
    ],
    id: '01DK9EDP1GZ0WHGVP092WAJ94K',
    opacity: 1,
    pageIndex: 0,
    createdAt: '2019-08-27T13:47:19.728+02:00',
    updatedAt: '2019-08-27T13:47:28.235+02:00',
    name: '01DK9EDP1GZ0WHGVP092WAJ94K',
    color: '#FFD83F',
    icon: 'comment',
    text: 'test annotatioon from windows'
  }
```

Expected time shown for this example annotation: 13:47
Current time shown for the example annotation: 15:47

# Acceptance Criteria

- [ ] Timestamps and their timezone information are parsed correctly and are shown in the users local time

**Comment by leoek** [comment]
>Just to confirm, the Instant JSON payload above was exported from UWP without any alterations. Correct?

Yes it was exported without any alterations.

> examples, on my device which is on North American Eastern Time, which is UTC (Zulu) time -4, I am getting 9:47, which is the expected value.

The expected value for you would be 7:47. `2019-08-27T13:47:19.728+02:00` is central european time as indicated by the +2. If you convert that to zulu it would be `2019-08-27T11:47:19.728Z`, which translates into 7:47 for -4.

**Comment by leoek** [comment]
You can do a quick test in your browser with moment here: http://jsfiddle.net/remus/rLjQx/

If you enter this
```
var a = moment("2019-08-27T13:47:19.728+02:00").format('HH:mm');
alert(a);
```

**Comment by douglashill** [comment]
Since this is an issue with our iOS SDK I’m going to close this issue. We’ll keep you updated via our support platform.

**Comment by leoek** [comment]
@douglashill Please reconsider closing this issue, as it is not resolved yet. This seems like an especially important information for users of the react-native wrapper because those users will expect cross-platform compatibility.

I would also prefer updates in the github issue, as we can link github issues in our internal tickets. (Zendesk Support Requests seem to belong top only one user and need an exra account/authentication.)

**Comment by nickwinder** [comment]
@leoek I'm happy to say, a fix has been implemented and will now go through QA. As long as QA goes well, you will be seeing the fix in the next iOS release. 
I'll close this issue now, but feel free to reopen if there are any further issues after the next minor iOS release.
