### ISSUE TITLE
[UWP] creatorName is missing from exported Annotations

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#281]
# Details

Annotations which are exported on Windows are missing the `creatorName` prop. Also the prop [`annotationAuthorName` which is available on Android and IOS](https://github.com/PSPDFKit/react-native/blob/6ac3fb93b20ec7f8057ec7b8001baec41c4a1071/index.js#L496) is missing in the `index.windows.js`

**Example**

```
<PSPDFKitView
            annotationAuthorName={"John Doe"}
...
```

Resulting Annotation:
```diff
      {
        v: 1,
        type: 'pspdfkit/note',
        bbox: [
          172.03778076171875,
          300.9306945800781,
          24,
          24
        ],
        id: '01DKBQNFZKQ9ZVH8EXPHGJ1RW6',
        opacity: 1,
        pageIndex: 0,
+      creatorName: 'John Doe'
        createdAt: '2019-08-28T11:07:21.715+02:00',
        updatedAt: '2019-08-28T11:07:24.661+02:00',
        name: '01DKBQNFZKQ9ZVH8EXPHGJ1RW6',
        color: '#FFD83F',
        icon: 'comment',
        text: 'asdadsaad'
      }
```
# Acceptance Criteria

- [ ] The Annotation author is configurable through the property `annotationAuthorName` (should behave like[ IOS and Android](https://github.com/PSPDFKit/react-native/blob/6ac3fb93b20ec7f8057ec7b8001baec41c4a1071/index.js#L496))
- [ ] The Annotation author is set as creatorName in exported annotations (the annotation json must match the json of ios and android)

**Comment by leoek** [comment]
@nickwinder 

the `creatorName` of annotations should not be modified if they are added with `addAnnotation`
the `creatorName ` of annotations should be set for any new annotation which is created thorugh the ui

**Comment by nickwinder** [comment]
This was fixed in https://github.com/PSPDFKit/react-native/pull/292
