### ISSUE TITLE
[Android] Question: How can I disable that android saves the annotations into the pdf?

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#282]
# Details

In ios there is a configuration option named `autosaveEnabled` which stops the ios sdk from overwriting the pdf with the pdf which includes the annotations. How can I configure rn-pspdfkit android to behave like that?

# Acceptance Criteria

**Comment by irgendeinich** [comment]
I opened PR #289 to add the missing configuration option on Android.
