### ISSUE TITLE
[UWP] escaped double quotes block annotations from being added, escape characters are rendered in the annotation

### ISSUE THREAD

**Issue by leoek** [PSPDFKit/react-native#286]
# Details

Pspdfkit escapes double quotes like this in the exported annotation json `\"`. If an annotation with escaped double quotes (exactly as it was exported from pspdfkit) is added with `addAnnotation` the Annotation won't be addeed and the promise will be rejected with the following error: `Exception while trying to CreateAnnotationAsyncInternal: JSON.parse Error: Invalid character at position:449`

Replacing any ``\"` with ``"` in the text of the annotation before adding it resolves the issue temporary. (The annotation will be added successfully)

**Steps To Reprdouce**

1. Create text annotation on windows with the text `a"b`
2. Export the annotation json
3. Try to import the exported annotation json with `addAnnotation`

These `\` which are not supposed to be in the annotation json also cause issues with the rendering of the annotation in ios/android:

**Example Annotation**

```
{
    v: 1,
    type: 'pspdfkit/note',
    bbox: [
      361.6600036621094,
      366.3999938964844,
      24,
      24
    ],
    id: '01DKEK39WCA5Y0VQHARSKWK2KC',
    opacity: 1,
    pageIndex: 0,
    createdAt: '2019-08-29T13:33:55.739+02:00',
    updatedAt: '2019-08-29T13:45:20.951+02:00',
    name: '01DKEJEJWVVN43SFVS3X3WYACQ',
    creatorName: 'Anr APPB01 Tit APPB01 - ganz langer Titel a. Vorname (APPB01) A. Nachname (alles, APPB01, Alleskönner)',
    color: '#FFD83F',
    icon: 'comment',
    text: 'a\\"b\\n\\n\\njjj'
  }
```

**Render Result on Windows** (after replacing `\"` with `"` otherwise the annotation won't be imported at all)

![windows](https://user-images.githubusercontent.com/9424038/63939150-e04b0a80-ca66-11e9-8c52-41575cc2fb93.png)

**Render Result on IOS**

<img width="334" alt="Screenshot 2019-08-29 at 14 05 42" src="https://user-images.githubusercontent.com/9424038/63939277-27d19680-ca67-11e9-8a33-db69baa60bde.png">

# Acceptance Criteria

- [ ] Annotations which contain `\"` in the text of the annotation can be added with `addAnnotation`.
- [ ] The annotation text stays the same during importing and exporting on windows and android/ios.

**Comment by leoek** [comment]
@nickwinder Did you have a look at this? This is a blocker for us as it is possible to create annotations on windows which can't be imported on windows again. Also it prevents us from syncing windows annotations to IOS or Android.

**Comment by nickwinder** [comment]
@leoek I looked into this and it does indeed seem that UWP is not dealing with escape sequences correctly. 
I've added an issue internally to look into it this. 

For now, I would have to ask for now to escape a `\` you have to double escape it. i.e `\\\\` produces a `\`. 
I've tested this with the annotation you provide about and I receive `a\"b\n\n\njjj` as the contents.

**Comment by leoek** [comment]
@nickwinder 

I think you misunderstood me a bit. If I add a note with the text `a"b`, the resulting annotation json on windows is

```

**Comment by leoek** [comment]
>For now, I would have to ask for now to escape a \ you have to double escape it. i.e \\\\ produces a \.

This seems to be a second issue. I have just tried to make a note with the text `a\b` which produces the following annotation json:
```
{
      v: 1,
      type: 'pspdfkit/note',
      bbox: [
        388.8377990722656,
        541.5999755859375,
        24,
        24
      ],
      id: '01DKYD7GPQF2834BQ8D9JYMTT5',
      opacity: 1,
      pageIndex: 0,
      createdAt: '2019-09-04T17:10:32.152+02:00',
      updatedAt: '2019-09-04T17:10:36.677+02:00',
      name: '01DKYD7GPQF2834BQ8D9JYMTT5',
      color: '#FFD83F',
      icon: 'comment',
      text: 'a\\b',
      creatorName: 'a. Vorname (APPB01) A. Nachname (alles, APPB01, Alleskönner)'
    }
```
Which is than rendered like this
![Unbenannt](https://user-images.githubusercontent.com/9424038/64267869-6bc90d80-cf37-11e9-8c68-9d8aca46d3ac.PNG)

**Comment by leoek** [comment]
And than there are line breaks in which `\n` is escaped as `\nn`. This works fine within windows.

The note
```
a
b
c
d
```

is exported as 

```
{
      v: 1,
      type: 'pspdfkit/note',
      bbox: [
        446.4377746582031,
        155.1999969482422,
        24,
        24
      ],
      id: '01DKYD5VD40ED2WFPBZH27WACM',
      opacity: 1,
      pageIndex: 0,
      createdAt: '2019-09-04T17:09:37.573+02:00',
      updatedAt: '2019-09-04T17:09:44.959+02:00',
      name: '01DKYD5VD40ED2WFPBZH27WACM',
      color: '#FFD83F',
      icon: 'comment',
      text: 'a\\nb\\nc\\nd',
      creatorName: 'a. Vorname (APPB01) A. Nachname (alles, APPB01, Alleskönner)'
    }
```

Importing this annotation json on windows works fine and renders as expected, but importing the same annotation json on IOS will render `a\\nb\\nc\\nd` instead of the original note.

**Comment by nickwinder** [comment]
> I think you misunderstood me a bit. If I add a note with the text a"b, the resulting annotation json on windows is

Ok I understand now, so there is a bug here where the input format of `content` requires a different format to the output format of `content`. 
I'll add this extra information to the internal issue. 

> This seems to be a second issue. I have just tried to make a note with the text a\b which produces the following annotation json:

To achieve this currently you would have to added an annotation with the content of `a\\\\b`, although the read back format of this in `onAnnotationsChanged` and `getAnnotations` would read `a\\b` due to the previous issue mentioned.

> And than there are line breaks in which \n is escaped as \nn. This works fine within windows.

Yes it seems that `\n` imports and exports as a new line ok on windows, but I see that this is not consistent with the other platforms. 
I will also add this information to the internal issue.

**Comment by leoek** [comment]
@nickwinder 
Thanks. I will check whether I can implement a workaround to sanitize the escaping for the exported annotations until this is fixed within the windows sdk. (This is one of our current blockers as it is directly visible to the user.)

**Comment by leoek** [comment]
@nickwinder do you have a timeline for this issue?

**Comment by nickwinder** [comment]
@leoek Yeah, we're just waiting for the next UWP release to come out. As long as QA is good, we're look at this week. Then we'll be able to close this issue out.

**Comment by leoek** [comment]
That sounds good, Thanks!

**Comment by nickwinder** [comment]
I've just updated the https://github.com/PSPDFKit/react-native/tree/windows-support branch. I tested the issue against the new update and all seems to work as expected. 
Feel free to re-open this issue if you find anything you believe is incorrect.

**Comment by leoek** [comment]
@nickwinder Thanks! We will merge these changes and report back with the results.

@Elmatoss @matchwerk-dev please test and integrate into our [mw/windows-support branch](https://github.com/matchwerk/react-native-pspdfkit/tree/mw/windows-support)
