### ISSUE TITLE
View controller-based status bar appearance

### ISSUE THREAD

**Issue by PvanHengel** [PSPDFKit/react-native#30]
Hi,

Sorry for posting a "question" here, but this is probably very helpful to others, and should be updated in the docs.  When using the latest react native >0.48 when you Change "View controller-based status bar appearance" to YES in Info.plist the app won't start, it throws the error:  

RCTStatusBarManager module requires that the UIViewControllerBasedStatusBarAppearance key in the Info.plist is set to NO.  If you set it to NO, the app will start, but obviously the plugin throws an error.  Any help would be great in fixing this conflict.

**Comment by radazzouz** [comment]
Hi @PvanHengel !

PSPDFKit requires `UIViewControllerBasedStatusBarAppearance` mode to be set to YES in your Info.plist file:

https://pspdfkit.com/guides/ios/current/faq/view-controller-based-status-bar-appearance/

See the issue we've filed in the React Native repo: https://github.com/facebook/react-native/issues/11710

Since this is a React Native issue, I'll be closing this issue.

Thank you!

**Comment by PvanHengel** [comment]
Thank yo for pointing this issue to the react discussion, which was closed, and now simply a discussion topic.  More tactically - is there a recommended solution for "production" react native apps?  Should we leave it set to NO and suppress the error that PSPDFKIT throws?  I suspect if we do it the other way around, eg ignore the react native error the app wont boot, since it a "redscreen" error that react native throws.

**Comment by radazzouz** [comment]
> Should we leave it set to NO and suppress the error that PSPDFKIT throws?

Can you surprise the error and get the app to launch properly? If so, then are you able to use PSPDFKit?

BTW, how are you surprising the error?

**Comment by steipete** [comment]
Pvan, thanks for commenting on the related React Native issue. One solution is to adopt react-native-navigation, which both offers a better experience and supports both modes:

https://github.com/wix/react-native-navigation/blob/master/ios/RCCViewController.m

**Comment by SuTran** [comment]
Hi @steipete,

I'm currently facing with this issue. Could you help me on how adopting `react-native-navigation` could solve this. After using that library, which option should I choose for "View controller-based status bar appearance"?
My app is using `react-navigation` therefore I need to update my code also.

**Comment by steipete** [comment]
@SuTran I only found the reference while googling. Not the expert here. I suggest posting your question on https://stackoverflow.com
