### ISSUE TITLE
Configuration Options

### ISSUE THREAD

**Issue by PvanHengel** [PSPDFKit/react-native#31]
The config options provided are somewhat limited, for example there is not a way to control which buttons are displayed, we want to hide some of them like the send to button, also you are unable to set the title bar or button colors, only the background color.  The options provided work well though.  

Perhaps the docs could be updated to explain how to configure this globally on the n active side, or better would be to expose more config options via the JavaScript config object.

**Comment by radazzouz** [comment]
We try to keep the React Native bindings for PSPDFKit very simple. We made them open source so everyone can extend them as needed.

Not every UI customization can be achieved via a `PSPDFConfiguration` property and not all UI customizations have a JavaScript interface yet. So we welcome pull request contributions ;) 

Here's how to customize the tool bar: https://pspdfkit.com/guides/ios/current/customizing-the-interface/configure-the-toolbar

**Comment by PvanHengel** [comment]
I have tried several ways of changing the default colors for the buttons and header styles as per your link by making modifications to the RCT_EXPORT_METHOD(present:(PSPDFDocument *)document withConfiguration:(PSPDFConfiguration *)configuration) { ... in the module, but it doesn't seem to have any effect.  There is a note about doing it "early" in the app, but how do we do that within the wrapper?  Is there a way we can pass or set these props the same way we set the license key, or pass the base config?

**Comment by radazzouz** [comment]
Are you referring to `UIAppearance`? 

https://pspdfkit.com/guides/ios/current/customizing-the-interface/appearance-styling/

If so, then you can you can see how we do it in `-[PSCatalogViewController applyCatalogAppearanceUsingCustomTinting:]` in the Catalog app.
