### ISSUE TITLE
[Android] Missing support for annotation background color

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#313]
# Details
1. On Android you can not set a background color to a drawn annotation. But on Windows/iOS that *is* possible.
2. Annotation backgrounds created on Windows/iOS are not visible for the android user.

#### Windows/iOS
![grafik](https://user-images.githubusercontent.com/40574856/67409967-a1938580-f5bb-11e9-8716-7a4d83473a02.png)
#### Android
![grafik](https://user-images.githubusercontent.com/40574856/67410026-bff98100-f5bb-11e9-8993-b92639c1c101.png)

# Acceptance Criteria

- [ ] Ability to configure background colors on android
- [ ] Display already set background colors on android

**Comment by leoek** [comment]
@irgendeinich any progress?

**Comment by irgendeinich** [comment]
@leoek 
Thanks for the ping. 

Sadly this will require a framework update as this needs to be fixed there first. I created an internal ticket and linked it to this one. Once there is an update we'll also update you here.

**Comment by leoek** [comment]
@irgendeinich Thanks for the update. This will be one of the steps to get annotations work across platforms.

**Comment by irgendeinich** [comment]
Starting with release https://github.com/PSPDFKit/react-native/releases/tag/1.26.7 using version 6.1.1 of the framework this should now work correctly on Android.

I'm going to close this, should this still be an issue for you after updating, feel free to reopen this issue.
