### ISSUE TITLE
[Android] Annotation timestamp inconsistency

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#328]
# Details
The information about an annotation displays an user name and a timestamp.

If one creates/changes an annotation the current behaviour is as follows: 

- Android: Creator name and createdAt timestamp is displayed
- iOS: Creator name and createdAt timestamp is displayed
- Windows: Creator name and **changedAt** timestamp is displayed

This behaviour is pretty confusing for the user. We would like to display the creation timestamp in windows aswell, if one changes an annotation. 

# Acceptance Criteria

- [ ] Consistent behaviour on all platforms

**Comment by nickwinder** [comment]
Thanks for bringing this up. 
Can I just confirm that you are referring to the timestamps seen in the annotation overview toolbar? As seen in the following screenshot.
<img width="299" alt="Screen Shot 2019-11-15 at 9 21 30 AM" src="https://user-images.githubusercontent.com/16980993/68954294-5a974b00-0789-11ea-9d60-645085966729.png">

**Comment by Elmatoss** [comment]
Yes @nickwinder

**Comment by steipete** [comment]
This is a platform inconsistency. IMO Web/Windows do the right thing here, as changedAt is probably the more interesting data point.

We'll discuss this internally and follow up.

**Comment by nickwinder** [comment]
@Elmatoss After testing Windows, Android, and iOS. I find slightly different results. 

- iOS. Date shown is the `changedAt`/`lastmodified` timestamp. Further, backed up by looking that the code internally.
- Windows. Date shown is the `changedAt`/`lastmodified` timestamp.
- Android. Date shown is the `createdAt` timestamp.

From this, we can see that Android has the incorrect behavior, and as @steipete mentions, iOS and Windows hold the most correct implementation of using the `changedAt`/`lastModified` timestamp. 

Please can you confirm the behavior on iOS? As my findings seem to differ to yours. If not we need to investigate this.

I will file an internal issue on Android to bring the behavior inline with Windows and iOS.

**Comment by Elmatoss** [comment]
> Please can you confirm the behavior on iOS?

My fault sorry, it's `changedAt` on iOS/Windows and `createdAt` on Android. 

We'd like it either way, it just should be consistent on all platforms

**Comment by leoek** [comment]
And we would like the name and date to be consistent as well:
-  If the name is the creator, the date should be the creation date
- if the name is the last person which changed something, the date should be the changedAt date

currently we would prefer to have the creation date and the original author. also it would make sense from our perspective to show both timestamps

**Comment by nickwinder** [comment]
@leoek We take your feedback onboard, and I've attached your comments to currently open internal ticket for further discussion.

**Comment by leoek** [comment]
@nickwinder @steipete any progress on this?

**Comment by nickwinder** [comment]
It's looks the behavior in Android was changed with PSPDFKit for Android 6.1.1, and I see the wrapper is based from 6.2.0. Therefore, you will be seeing consistency across all platforms now. 
I apologize this was not communicated earlier.
