### ISSUE TITLE
[UWP] Windows-support branch is missing a proper version

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#333]
# Details

You recently merged #331 into the windows-support branch, however the version bump in the package.json and the related git tag are missing.

Could you please follow up on that, bump the version and add the related tag?

# Acceptance Criteria

- [ ] Every merge to a branch that contains stable versions which are used in production should include a version bump.

**Comment by nickwinder** [comment]
@Elmatoss I apologize for missing the tag for the windows update. 
There is no bump in the `package.json` as this is on the `windows-support` branch and maintained to allow forking of the repo, and apply any type of customization and cherry-picking of new features on top of this branch. For example, https://github.com/matchwerk/react-native-pspdfkit/tree/mw/windows-support
