### ISSUE TITLE
[Windows] New licence key not working

### ISSUE THREAD

**Issue by Elmatoss** [PSPDFKit/react-native#340]
# Details

I  replaced the old licence key with the new one in the `App.xaml` file, but as soon as I try to open a pdf the app crashes with the exception `Failed to initialize PSPDFKit: undefined`

It works seamlessly with the old one. 
Additionally your page for windows licence key integration is not working https://pspdfkit.com/guides/windows/current/getting-started/adding-the-license-key/ . 

Would be awesome, if you fixed that too.

# Acceptance Criteria

- [ ] Windows Licence Key is working properly

**Comment by nickwinder** [comment]
@Elmatoss 
I've managed to try out your license and I've got it working fine. 
I believe you may have a bundle ID issue. You must make sure that the Package Name of your application matches the bundle ID registered on your PSPDFKit customer account. As explained in https://pspdfkit.com/guides/windows/current/faq/what-is-a-bundle-id/. 

I have noticed that the react-native instructions did not mention this and have added extra notes to ensure there is no confusion. Thank you for bring this up. 

Lastly, please could you tell me where you found the link for pspdfkit.com/guides/windows/current/getting-started/adding-the-license-key? This page does not exist and if there are any references we need to fix that.

**Comment by GaraGentor** [comment]
@nickwinder @Elmatoss 
I had the same problem and it seems that this is the correct answer! Thanks a lot Nick, now PSPDFKit is showing the Documents without this error. Could anyone update this information in the Windows Readme? I think without this information many people run into this error if they are not familiar with visual studio.

**Comment by leoek** [comment]
Hi @nickwinder

**Comment by leoek** [comment]
Hi @nickwinder 

The broken link ist on the customer page (https://customers.pspdfkit.com/) and is displayed after clicking the blue license key button.

I am sure that we are using the correct bundle id. This was just a license renewal and we did not change the bundle id + if we use the old license key everything is working fine. Also `<Identity Name=` from Pacakge.appxmanifest matches the assigned bundle id on the customers page.

Our App.xaml has the folliowing content:

```
﻿<rn:ReactApplication
    x:Class="appname.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:rn="using:ReactNative"
    RequestedTheme="Light">

    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary>
                    <x:String x:Key="PSPDFKitLicense">licensekey_from_customers_page_here</x:String>
                </ResourceDictionary>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>

</rn:ReactApplication>
```

Any ideas what the issue could be?

**Comment by leoek** [comment]
@Elmatoss 

I have just notices that the json export of the licenses adds `\n`s into the license keys :see_no_evil: Can you please double-check that you did not copy the `\n`s into the config?

@nickwinder 

It's pretty unexpected and arguably incorrect that there are `\n`s inside the license strings in the license json. The license json was exported from the customer panel (https://customers.pspdfkit.com/) via the "export license keys (json)" button on the top right.

**Comment by nickwinder** [comment]
@leoek 
I agree with you, you should not be seeing `\n` in the key. 

Let me know if this sorts the issue.

I can see how these two issue can cause much confusion, so I'll raise the issue about the erroneous link and the format of the key in the customer panel.

Thanks for the help from your team.

**Comment by Elmatoss** [comment]
@nickwinder 
@leoek was right, the error was due to the `\n`.
I did not double check the licence key string, but now it works fine, thank you!
