### ISSUE TITLE
Question: iOS - delete menu buttons

### ISSUE THREAD

**Issue by marksturm** [PSPDFKit/react-native#35]
Hell-o ;-)

I tried today very hard to customize the psdpdfkit for my first react-native app. After like 12 Hours i got this on Android and im Happy...

<img width="611" alt="screenshot 2017-10-26 21 30 46" src="https://user-images.githubusercontent.com/3530788/32073021-f3bd3662-ba94-11e7-91d9-ad25d99abad5.png">

I spend like the past 4 hours of try and fail to customize the same on iOS. I have simple no experience in Objetive-C or Swift - i just need a good hint, how i can get rid of unwanted (pink ones) menuparts.

![pink](https://user-images.githubusercontent.com/3530788/32072962-cd87cd5e-ba94-11e7-8e79-741b3f7980f4.jpg)

**Comment by radazzouz** [comment]
@marksturm, 

We try to keep the React Native wrapper for PSPDFKit very simple. We made them open source so everyone can extend them as needed. 

There currently is no JavaScript API to customize the toolbar yet, but we welcome pull request contributions ;)

Here's how to customize the tool bar: https://pspdfkit.com/guides/ios/current/customizing-the-interface/configure-the-toolbar

In your case, you can add

```
  pdfViewController.navigationItem.rightBarButtonItems = @[pdfViewController.outlineButtonItem, pdfViewController.searchButtonItem];

```

to `[RCTPSPDFKitManager present:withConfiguration:]`.

It should look like this:

```ObjC
RCT_EXPORT_METHOD(present:(PSPDFDocument *)document withConfiguration:(PSPDFConfiguration *)configuration) {
  PSPDFViewController *pdfViewController = [[PSPDFViewController alloc] initWithDocument:document configuration:configuration];

  pdfViewController.navigationItem.rightBarButtonItems = @[pdfViewController.outlineButtonItem, pdfViewController.searchButtonItem];
  
  UINavigationController *navigationController = [[UINavigationController alloc] initWithRootViewController:pdfViewController];

  UIViewController *presentingViewController = RCTPresentedViewController();
  [presentingViewController presentViewController:navigationController animated:YES completion:nil];
}
```

Here's how your toolbar should look:

<img width="372" alt="screenshot" src="https://user-images.githubusercontent.com/7443038/32074046-35428666-ba66-11e7-82bf-307362117e9b.png">

I’m going ahead and close this issue, but please feel free to follow up in here if anything is unclear or ping us on our support ticket platform for any other issues.

https://pspdfkit.com/support/request

Thanks!

**Comment by marksturm** [comment]
thank you so much!
