### ISSUE TITLE
[Android] menuItemGrouping lost when switching between Default/Night

### ISSUE THREAD

**Issue by wbercx** [PSPDFKit/react-native#359]
# Details
`menuItemGrouping` configuration is lost when switching between Default and Night themes. You end up getting every menu item after switching.

![switching](https://user-images.githubusercontent.com/2244710/76930098-d3760180-6939-11ea-8786-c45253e2e2af.gif)

# Acceptance Criteria
Grouping to stick around.

**Comment by irgendeinich** [comment]
Thanks for reporting this. I'm gonna have a look and create a PR as soon as possible.

**Comment by irgendeinich** [comment]
I just released 1.29.0 which contains a fix for this, should this still make issues feel free to reopen this issue.

**Comment by wbercx** [comment]
> I just released 1.29.0 which contains a fix for this, should this still make issues feel free to reopen this issue.

@irgendeinich Yup, the menu item grouping seems to work just fine now. The back button still disappears though. Do you want me to open a new issue for that?
