### ISSUE TITLE
Question: iOS Disable Document Label and disable Annotations

### ISSUE THREAD

**Issue by marksturm** [PSPDFKit/react-native#38]
Hi,
im just two steps away from submit the app into the store, but i have 3 small issues left and i was not able to find a solution so far ... just because of null skills.

**Document Label**
I would like disable the document label, just simple turn it completly off.
<img width="373" alt="title" src="https://user-images.githubusercontent.com/3530788/32688539-c33f43e6-c6d2-11e7-95be-d48436c57791.png">
I made this on android with simple configuration.hideDocumentTitleOverlay();

**Annotations**
I really want to turn the whole annotation-part off. No text-/image selection, highlighting, speach or anything.

**Tint Color**
I would like to change the color, of the outlineframe at the thumbnails? What is the "name" of the outline-element?
<img width="93" alt="tint" src="https://user-images.githubusercontent.com/3530788/32688572-b549fd7a-c6d3-11e7-8a7e-878aa14004a3.png">

It would be really kind if someone could help,  im startin to get desperate.

**Comment by steipete** [comment]
Mark, as part of your commercial PSPDFKit license, you get free support. Ideally, ping us on https://pspdfkit.com/support/request/ and we'll help you out.

See here how to disable annotation editing:
https://pspdfkit.com/guides/ios/current/features/controlling-pdf-editing/

Here's how you disable the document label:
https://pspdfkit.com/api/ios/Classes/PSPDFConfiguration.html#/c:objc(cs)PSPDFConfiguration(py)documentLabelEnabled

**Comment by steipete** [comment]
I've added support for editableAnnotationTypes

https://github.com/PSPDFKit/react-native/commit/15f61abf31a54344aef7d3052abfb55b931ba48c

Here's how you set the document label:

`documentLabelEnabled: true`
