### ISSUE TITLE
Integrating the Dynamic Framework

### ISSUE THREAD

**Issue by marksturm** [PSPDFKit/react-native#39]
The example for iOS misses the run-script part. It will work on debug and release mode on every device without it, but if you try to submit the app to the store it turns into signing errors.

https://pspdfkit.com/guides/ios/current/getting-started/integrating-pspdfkit/#toc_integrating-the-dynamic-framework

**Comment by radazzouz** [comment]
@marksturm thanks for reporting! We'll mention the phase script in the README.

In the meantime, if you want to submit a PR, please feel free to do it.

If you choose to do so, please make sure that you sign our [CLA](https://github.com/PSPDFKit/react-native#contributing)

Thanks!
