### ISSUE TITLE
Add API to change current visible spreadIndex

### ISSUE THREAD

**Issue by steipete** [PSPDFKit/react-native#46]
Add API to change current visible spreadIndex on iOS.

Think about naming so this also fits into the Android world.

**Comment by radazzouz** [comment]
On iOS it was added in https://github.com/PSPDFKit/react-native/pull/98 for the UI component, and we already had it for the native Module https://github.com/PSPDFKit/react-native/blob/master/ios/RCTPSPDFKit/RCTPSPDFKitManager.m#L46

We already have this on Android too.
