### ISSUE TITLE
Where can i found the pspdfkit-2.7.aa?

### ISSUE THREAD

**Issue by imarem** [PSPDFKit/react-native#5]
I'm trying install the module in an ndroid device.

In a point 9 of the android "Getting Start"
9.- Copy pspdfkit-*.aar library in YourApp/android/pspdfkit-lib.

and my PSPDFKit for Android download, are pspdfkit-2.9.1.aar not pspdfkit-2.7.aar

Could be a problem?

**Comment by steipete** [comment]
We don't offer old version for demo downloads. Simply use pspdfkit-2.9.1.aar - it will work just fine.
