### ISSUE TITLE
Open an encrypted PDF automatically

### ISSUE THREAD

**Issue by kutayKoc** [PSPDFKit/react-native#51]
Hi,
I have an encrypted PDF and password. I want to open this pdf automatically . how can i do this? Are there any solutions?

**Comment by radazzouz** [comment]
Kutay, as part of your commercial PSPDFKit license, you get free support. Ideally, ping us on https://pspdfkit.com/support/request/, and we'll help you out.

At the moment, we don't have JavasScript wrapper for automatically decrypting/unlocking PDFs.

See here how to decrypt a PDF document in-memory:
https://pspdfkit.com/guides/ios/current/security/introduction-to-encryption/#toc_pspdfkit-supports-fast-in-memory-aes256-decryption

You will also find several native examples (like `PSCPasswordPresetExample`) in the Catalog app in the Security group.

I'll mark this issue as a feature request, but I can't give you any timeframe for the implementation. Any code contributions are very welcome; they would surely be reviewed and added.

**Comment by kutayKoc** [comment]
Thank for your answer. I examined your link . This link is about iOS. Are there any solution like this for android?Thank you...

**Comment by tomassurin** [comment]
As @radazzouz stated above, we don't have JavaScript wrapper for encrypting/decrypting PDFs.

See `AesEncryptedFileExample` in (Android) catalog app for an example of how to open AES encrypted files. 

If you just want to open password protected document automatically when launching `PdfActivity`, just pass `password` parameter to `PdfActivityIntentBuilder`, we have an example in our [guides](https://pspdfkit.com/guides/android/current/getting-started/using-activity/#toc_more-options).

**Comment by kutayKoc** [comment]
Thank for your answer. I solved my problem. I sent the password parameter. Thank you for your attention.
