### ISSUE TITLE
Allow embedding iOS PSPDFViewController as React View

### ISSUE THREAD

**Issue by steipete** [PSPDFKit/react-native#54]
Add a react native view component to embed the `PSPDFViewController` as a view next to the modal presentation via `PSPDFKit.present`.

# Details
This will require some trickery to correctly attach the view controller into the react hierarchy, but we can use something like our internal `pspdf_closestViewController` to crawl up the hierarchy and correctly attach us for the required view events.

Add a split screen example similar to the "Merge Annotations Interface" example in our catalog (`PSCMergeDocumentsExample.m`) to showcase how useful this can be.

# Acceptance Criteria
- [ ] New react native view component 
- [ ] Split screen example
- [ ] Update readme documentation

**Comment by novellizator** [comment]
please make it for android too!

**Comment by steipete** [comment]
@novellizator Step by step. That's the plan. We need to see how well this works for iOS, and what our options are for Android to add a Fragment, or if we need to change to a view. Separate future ticket.
