### ISSUE TITLE
Allow embedding Android PdfFragment as React View

### ISSUE THREAD

**Issue by irgendeinich** [PSPDFKit/react-native#58]
Add a react native view component to embed the `PdfFragment` as a view next to the modal presentation via `PSPDFKit.present`.

# Details
This is going to be non trivial as react by default only allows embedding `View`s but we need to embed a `Fragment`. To further complicate things the `ReactActivity` used by default doesn't extend from `FragmentActivity` so user will need to change their Java code to make this work.

# Acceptance Criteria
- [ ] New react native view component 
- [ ] Split screen example
- [ ] Update readme documentation

**Comment by irgendeinich** [comment]
I already looked into ways to attach a `Fragment` to the react view hierarchy and got it to work as long as react is running in a `FragmentActivity` subclass (we can provide one for our users that works the same as the `ReactActivity`), so that's not going to be an issue when building this.

Right now what's blocking us is react-native not correctly calling layout methods on non react views in the hierarchy.
See https://github.com/facebook/react-native/issues/17968
This means that any `PdfFragment` we add won't work since layout changes that are not caused by react will have no effect.

**Comment by Liestambeur** [comment]
Hi, 
is it now possible to render a pdfFragment as a reactView? If so is it possible to add a small example?
Lies

**Comment by yestay90** [comment]
Does pdfFragmentTag supported now?

**Comment by irgendeinich** [comment]
Yes this is fully supported now, if you checkout the Catalog we have many samples that integrate our `PSPDFKitView` into the react view hierarchy on both Android and iOS.

**Comment by yestay90** [comment]
@irgendeinich I create issue, can you look at it please? 
https://github.com/PSPDFKit/react-native/issues/352
