### ISSUE TITLE
Programmatic PDF form filling in React Native

### ISSUE THREAD

**Issue by steipete** [PSPDFKit/react-native#70]
We want to add API that allows programmatic API access to the PDF AcroForm data model, including text, checkboxes, radio buttons, etc.

The API should both allow programmatic form filling and also data extraction.

Use Instant JSON?

**Comment by radazzouz** [comment]
## API:

getFormElement(fullyQualifiedName);
updateFormElement(json);

**Comment by radazzouz** [comment]
The iOS implementation PR: https://github.com/PSPDFKit/react-native/pull/106

**Comment by radazzouz** [comment]
Both the Android and iOS PRs have been merged. Closing.
