### ISSUE TITLE
Add a JavaScript callback for when document saved

### ISSUE THREAD

**Issue by radazzouz** [PSPDFKit/react-native#82]
## Details

We should add the ability to notify in JavaScript when a document is saved.

# Acceptance Criteria:

- [x] An `onDocumentSaved` JS handler is added.
- [ ] Platforms: iOS + Android

**Comment by radazzouz** [comment]
iOS PR #81

**Comment by irgendeinich** [comment]
Android PR https://github.com/PSPDFKit/react-native/pull/95
