### ISSUE TITLE
Add callback for when an annotation is tapped

### ISSUE THREAD

**Issue by radazzouz** [PSPDFKit/react-native#83]
## Details

Add the ability to notify in JavaScript when the user tapped on an annotation.
The tap should allow to stop or continue with default action processing.

On iOS, we should implement https://pspdfkit.com/api/ios/Protocols/PSPDFViewControllerDelegate.html#/c:objc(pl)PSPDFViewControllerDelegate(im)pdfViewController:didTapOnAnnotation:annotationPoint:annotationView:pageView:viewPoint:

# Acceptance Criteria:

- [ ] An `onAnnotationTapped` JS handler is added.
- [ ] Platforms: iOS + Android

**Comment by radazzouz** [comment]
iOS PR #88

**Comment by irgendeinich** [comment]
Android PR https://github.com/PSPDFKit/react-native/pull/95
