### ISSUE TITLE
Add catalog example for changing pages

### ISSUE THREAD

**Issue by radazzouz** [PSPDFKit/react-native#87]
## Description:

Add a catalog example which has a next page and previous page buttons. 

## Acceptance Criteria:

- [x] The catalog example shows how to implement a next/previous button using the JavaScript API
- [x] Platforms: iOS + Android

**Comment by SuTran** [comment]
Hi @steipete , @radazzouz 

Thanks a lot for working on this. We're currently looking this feature ready to be integrated into our app. Can you help to share the timeline working on this, so we can plan on our side accordingly.

Cheers,
Su Tran

**Comment by radazzouz** [comment]
Su Tran,

We don't have an ETA at the moment. Please subscribe to this issue to be notified when we reference the PR(s).

Thanks!

**Comment by irgendeinich** [comment]
Android PR https://github.com/PSPDFKit/react-native/pull/95

**Comment by radazzouz** [comment]
iOS PR https://github.com/PSPDFKit/react-native/pull/98

**Comment by radazzouz** [comment]
Both the Android and iOS PRs have been merged. Closing.
