### ISSUE TITLE
Execution failed for task ':react-native-pspdfkit:processReleaseResources'

### ISSUE THREAD

**Issue by sourabhkheterpal** [PSPDFKit/react-native#9]
Hi
When i trying to run app on emulator its give me error. not able to understand how solve this.

**Error:**

> :react-native-pspdfkit:processReleaseResources
/home/sourabh/canny/node_modules/react-native-pspdfkit/android/build/intermediates/exploded-aar/canny/pspdfkit-lib/unspecified/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'ThemeOverlay.AppCompat.Dialog.Alert'.
/home/sourabh/canny/node_modules/react-native-pspdfkit/android/build/intermediates/exploded-aar/canny/pspdfkit-lib/unspecified/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Widget.Design.BottomSheet.Modal'.
/home/sourabh/canny/node_modules/react-native-pspdfkit/android/build/intermediates/exploded-aar/canny/pspdfkit-lib/unspecified/res/values/values.xml:2 : Error retrieving parent for item: No resource found that matches the given name 'Theme.Design.Light.BottomSheetDialog'.
/home/sourabh/canny/node_modules/react-native-pspdfkit/android/build/intermediates/exploded-aar/canny/pspdfkit-lib/unspecified/res/values/values.xml:511:21-37 : No resource found that matches the given name: attr 'bottomSheetStyle'.

:react-native-pspdfkit:processReleaseResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-pspdfkit:processReleaseResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/home/sourabh/Android/Sdk/build-tools/25.0.2/aapt'' finished with non-zero exit value 1

**in android/app/build.gradle:**
` 
android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    dexOptions {
      javaMaxHeapSize "2g"
    }

    defaultConfig {
        applicationId "com.canny"
        minSdkVersion 16
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    signingConfigs {
        release {
            storeFile file(MYAPP_RELEASE_STORE_FILE)
            storePassword MYAPP_RELEASE_STORE_PASSWORD
            keyAlias MYAPP_RELEASE_KEY_ALIAS
            keyPassword MYAPP_RELEASE_KEY_PASSWORD
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
    buildTypes {
        release {
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
            signingConfig signingConfigs.release
        }
    }
    // applicationVariants are e.g. debug, release
    applicationVariants.all { variant ->
        variant.outputs.each { output ->
            // For each separate APK per architecture, set a unique version code as described here:
            // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
            def versionCodes = ["armeabi-v7a":1, "x86":2]
            def abi = output.getFilter(OutputFile.ABI)
            if (abi != null) {  // null for the universal-debug, universal-release variants
                output.versionCodeOverride =
                        versionCodes.get(abi) * 1048576 + defaultConfig.versionCode
            }
        }
    }
}
  dependencies {
     compile project(':react-native-pspdfkit')
    compile project(':pspdfkit-lib')
    compile project(':react-native-config')
    compile project(':react-native-fetch-blob')
    compile project(':react-native-fcm')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.facebook.react:react-native:+"  // From node_modules
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
      transitive = true
      }
  }
`

**Version**;
RN: 0.42.0
react-native-pspdfkit: 1.1.0
pspdfkit-2.9.3.aar
Android SDK Build tool 25.0.2 is already installed.

Thanks.

**Comment by simoarpe** [comment]
Hi @sourabhkheterpal,
Please open your Android SDK manager and verify you have all the Android dependencies installed and up to date
![screenshot 2017-04-07 10 15 11](https://cloud.githubusercontent.com/assets/3308503/24792082/def3a70a-1b7c-11e7-91bf-5d90d1b80d2d.png)
![screenshot 2017-04-07 10 22 31](https://cloud.githubusercontent.com/assets/3308503/24792105/f1097a3c-1b7c-11e7-9de1-37ac58644b4c.png)

Also updating to the last version of PSPDFKit is highly suggested, there are loads of improvements and bug fixes, you can download it from our [PSPDFKit Customer Portal](https://customers.pspdfkit.com/)

Step into your app folder and clean the cache running `yarn cache clean`.

Delete the `node_modules` folder (e.g. `YourApp/node_modules`).

Reinstall the dependencies running `yarn install`.

Navigate to `react-native-pspdfkit` module and open `android/build.gradle` (e.g. `YourApp/node_modules/react-native-pspdfkit/android/build.gradle`) and add again the dependencies for PSPDFKit (step 6 of our[ integration guide for Android](https://github.com/PSPDFKit/react-native#getting-started-1) ).

Let us know it this solves the issue and feel free to follow up if you have any further questions.

**Comment by sourabhkheterpal** [comment]
Thanks @simoarpe .
It works fine.

**Problem**: 
it works cool about 15 days back when i first setup this. after doing development, i have committed my code to  Repo where we generally don't commit node_modules code. so node_modules changes(for `react-native-pspdfkit` ) disappeared when i come back for further development on this branch.

**Just suggestion**: Ideally dependencies that we added in `YourApp/node_modules/react-native-pspdfkit/android/build.gradle` should't not be there because node_modules directory is not permanent. This thing took my more than half day :( 

Thanks a lot for the answer.
