### ISSUE TITLE
Add callbacks for when an annotation is added, changed or deleted

### ISSUE THREAD

**Issue by radazzouz** [PSPDFKit/react-native#90]
## Details

Add the ability to notify in JavaScript when an annotation is added, changed or deleted.

For iOS, see https://pspdfkit.com/guides/ios/current/annotations/detecting-if-annotations-have-changed/

# Acceptance Criteria:

- [ ] An `onAnnotationsChanged` JS handler is added.
- [ ] Platforms: iOS + Android

**Comment by radazzouz** [comment]
iOS implementation PR: https://github.com/PSPDFKit/react-native/pull/94

**Comment by irgendeinich** [comment]
Android PR https://github.com/PSPDFKit/react-native/pull/95
